#!/bin/bash
# Security Group (port 9008)

curl -X POST --header "Content-Type: application/json" --header "Accept: */*" -d '{
  "security_group": {
    "create_at": "string",
    "description": "string",
    "id": "3dda2801-d675-4688-a63f-dcda8d111112",
    "name": "sg2",
    "project_id": "3dda2801-d675-4688-a63f-dcda8d327f50",
    "security_group_rules": [
    ],
    "tenant_id": "3dda2801-d675-4688-a63f-dcda8d327f50",
    "update_at": "string"
  }
}' "http://localhost:9008/project/3dda2801-d675-4688-a63f-dcda8d327f50/security-groups"

