---
apiVersion: v1
kind: Service
metadata:
  name: alcor
  labels:
    app: alcor
spec:
  type: LoadBalancer
  selector:
    app: alcor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
