language: java

sudo: true

jdk:
  - oraclejdk13

before_script:
  - chmod +x ./scripts/build_coverage.sh

script:
  - ./scripts/build_coverage.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)