== [big blue]*Alcor Controller APIs*

The followings are the RESTful APIs of Alcor controller system.


[width="100%",cols="20%,10%,50%,20%"]
|===
|*Group* |*Method* |*Request*|*Response*

|<<VPCController>>
|*GET*
|xref:vpc_req_1[/project/{projectid}/vpcs/{vpcid}, /v4/{projectid}/vpcs/{vpcid}]
|

|
|*POST*
|/project/{projectid}/vpcs
|

|
|*PUT*
|/project/{projectid}/vpcs/{vpcid}
|

|
|*DELETE*
|/project/{projectid}/vpcs/{vpcid}
|

|
|*GET*
|/project/{projectid}/vpcs
|

|*Subnet Controller*
|*GET*
|/project/{projectid}/subnets/{subnetId}
|

|
|*POST*
|/project/{projectid}/subnets
|

|
|*PUT*
|/project/{projectid}/vpcs/{vpcid}/+
subnets/{subnetid}
|

|
|*DELETE*
|/project/{projectid}/vpcs/{vpcid}/
subnets/{subnetid}
|

|
|*GET*
|/project/{projectid}/vpcs/{vpcid}/subnets
|

|*Port Controller*
|*GET*
|/project/{projectid}/ports/{portId}
|

|
|*POST*
|/project/{projectid}/ports
|

|
|*PUT*
|/project/{projectid}/ports/{portid}
|

|
|*DELETE*
|/project/{projectid}/ports/{portid}
|

|
|*GET*
|/project/{projectid}/subnet/+
{subnetid}/ports
|

|
|*POST*
|/project/{projectid}/portgroup
|

|*Debug Controller*
|*GET*
|*/*
|

|
|*GET*|/debug|

||*GET* |/project/all/vpccount*|
||*GET*|/project/all/subnets|
|===

[[VPCController]]
=== [blue]*VPC Controller*

anchor:getVpcStateByVpcId[]*getVpcStateByVpcId*

* Method: GET

* anchor:vpc_req_1[]Request: /project/{projectid}/vpcs/{vpcid}, /v4/{projectid}/vpcs/{vpcid}

* Request Parameter: @PathVariable String projectid, @PathVariable String vpcid

* Response: VpcStateJson(vpcState)
....

....
anchor:createVpcState[]**createVpcState**

* Method: POST

* Request "/project/{projectid}/vpcs", "/v4/{projectid}/vpcs"

* Request Parameter: @PathVariable String projectid, @RequestBody VpcStateJson resource

* Response: VpcStateJson(vpcState)
....

....
anchor:updateVpcStateByVpcId[]**updateVpcStateByVpcId**

* Method: PUT

* Request /project/{projectid}/vpcs/{vpcid}", "/v4/{projectid}/vpcs/{vpcid}

* Request Parameter: @PathVariable String projectid, @PathVariable String vpcid, @RequestBody VpcStateJson resource

* Response: VpcStateJson(vpcState)
....

....
anchor:deleteVpcStateByVpcId[]**deleteVpcStateByVpcId**

* Method: DELETE

* Request /project/{projectid}/vpcs/{vpcid}", "/v4/{projectid}/vpcs/{vpcid}

* Request Parameter: @PathVariable String projectid, @PathVariable String vpcid, @RequestBody VpcStateJson resource

* Response ResponseId(vpcid)
....

....
anchor:getVpcStatesByProjectId[]**getVpcStatesByProjectId**

* Method: GET
* Request /project/{projectid}/vpcs
* Request Parameter: @PathVariable String projectid
* Response vpcStates
....

....

[[SubNetController]]
=== [blue]*Subnet Controller*

anchor:getSubnetStateById[]**getSubnetStateById**

* Method: GET

* Request: /project/{projectid}/subnets/{subnetId}, "/v4/{projectid}/subnets/{subnetId}"

* Request Parameter:

* Response: SubnetStateJson(subnetState)
....

....
anchor:createSubnetState[]**createSubnetState**

* Method: POST

* Request: "/project/{projectid}/subnets","v4/{projectid}/subnets"

* Request Parameter:

* Response: SubnetStateJson(subnetState)
....

....
anchor:updateSubnetState[]**updateSubnetState**

* Method: PUT

* Request: "/project/{projectid}/vpcs/{vpcid}/subnets/{subnetid}", "v4/{projectid}/vpcs/{vpcid}/subnets/{subnetid}"

* Request Parameter:

* Response: SubnetStateJson(subnetState)
....

....
anchor:deleteSubnetState[]**deleteSubnetState**

* Method: DELETE

* Request: "/project/{projectid}/vpcs/{vpcid}/subnets/{subnetid}", "v4/{projectid}/vpcs/{vpcid}/subnets/{subnetid}"

* Request Parameter:

* Response:
....

....
anchor:geSubnetStatesByProjectIdAndVpcId[]**geSubnetStatesByProjectIdAndVpcId**

* Method: GET

* Request: /project/{projectid}/vpcs/{vpcid}/subnets

* Request Parameter: @PathVariable String projectid, @PathVariable String vpcid

* Response: subnetStates
....

....

[[PortController]]
=== [blue]*Port Controller*

anchor:getPortStateById[]**getPortStateById**

* Method: GET

* Request: "/project/{projectid}/ports/{portId}", "v4/{projectid}/ports/{portId}"

* Request Parameter: @PathVariable String projectid, @PathVariable String portId

* Response: PortStateJson(portState)
....

....
anchor:createPortState[]**createPortState**

* Method: POST

* Request: "/project/{projectid}/ports", "v4/{projectid}/ports"

* Request Parameter: @PathVariable String projectid, @RequestBody PortStateJson resource

* Response: PortStateJson(customerPortState)
....

....
anchor:updateSubnetState[]updateSubnetState

* Method: PUT

* Request: "/project/{projectid}/ports/{portid}", "v4/{projectid}/ports/{portid}"

* Request Parameter: @PathVariable String projectid, @PathVariable String portid, @RequestBody PortStateJson resource

* Response: PortStateJson(currentPortState)
....

....
anchor:deletePortState[]**deletePortState**

* Method: DELETE

* Request: /project/{projectid}/ports/{portid}", "v4/{projectid}/ports/{portid}

* Request Parameter: @PathVariable String projectid, @PathVariable String portid

* Response: ResponseId(portid)
....

....
anchor:gePortStatesByProjectIdAndSubnetId[]**gePortStatesByProjectIdAndSubnetId**

* Method: GET

* Request: /project/{projectid}/subnet/{subnetid}/ports

* Request Parameter: @PathVariable String projectid, @PathVariable String subnetid

* Response: portStates
....

....
anchor:createPortStates[]**createPortStates**

* Method: POST

* Request: "/project/{projectid}/ports/{portId}", "v4/{projectid}/ports/{portId}"

* Request Parameter @PathVariable String projectid, @RequestBody PortStateGroup resourceGroup

* Response: response
....

....

[[DebugController]]
=== [blue]*Debug Controller*

anchor:index[]**index**

* Method: GET

* Request: /

* Request Parameter:

* Response: "Greetings from Alioth!"
....
.request
include::{snippets}/home/http-request.adoc[]

.response
include::{snippets}/home/http-response.adoc[]
....

anchor:getDebugInfo[]**getDebugInfo**

* Method: GET

* Request: /debug

* Request Parameter: value = "name", defaultValue = "World"

* Response: "Hello \{name}"
....
.request
include::{snippets}/getDebugInfo/http-request.adoc[]

.response
include::{snippets}/getDebugInfo/http-response.adoc[]
....

anchor:getVpcCountAndAllVpcStates[]**getVpcCountAndAllVpcStates**

* Method: GET

* Request: /project/all/vpccount

* Request Parameter:

* Response: Map
....
.request
include::{snippets}/getVpcCountAndAllVpcStates/http-request.adoc[]

.response
include::{snippets}/getVpcCountAndAllVpcStates/http-response.adoc[]
....
anchor:getVpcCount[]**getVpcCount**

* Method: GET

* Request: /project/all/vpccount

* Request Parameter:

* Response: Map
....
.request
include::{snippets}/getVpcCount/http-request.adoc[]

.response
include::{snippets}/getVpcCount/http-response.adoc[]
....
anchor:getAllSubnetStates[]**getAllSubnetStates**

* Method: GET

* Request: /project/all/subnets

* Request Parameter:

* Response: Map
....
.request
include::{snippets}/getAllSubnetStates/http-request.adoc[]

.response
include::{snippets}/getAllSubnetStates/http-response.adoc[]
....
