// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.futurewei.alioth.controller.schema;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code aliothcontroller.OperationType}
   */
  public enum OperationType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CREATE = 0;</code>
     */
    CREATE(0),
    /**
     * <code>UPDATE = 1;</code>
     */
    UPDATE(1),
    /**
     * <code>GET = 2;</code>
     */
    GET(2),
    /**
     * <code>DELETE = 3;</code>
     */
    DELETE(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CREATE = 0;</code>
     */
    public static final int CREATE_VALUE = 0;
    /**
     * <code>UPDATE = 1;</code>
     */
    public static final int UPDATE_VALUE = 1;
    /**
     * <code>GET = 2;</code>
     */
    public static final int GET_VALUE = 2;
    /**
     * <code>DELETE = 3;</code>
     */
    public static final int DELETE_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OperationType valueOf(int value) {
      return forNumber(value);
    }

    public static OperationType forNumber(int value) {
      switch (value) {
        case 0: return CREATE;
        case 1: return UPDATE;
        case 2: return GET;
        case 3: return DELETE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OperationType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OperationType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OperationType>() {
            public OperationType findValueByNumber(int number) {
              return OperationType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.futurewei.alioth.controller.schema.Common.getDescriptor().getEnumTypes().get(0);
    }

    private static final OperationType[] VALUES = values();

    public static OperationType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OperationType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:aliothcontroller.OperationType)
  }

  /**
   * Protobuf enum {@code aliothcontroller.EtherType}
   */
  public enum EtherType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>IPV4 = 0;</code>
     */
    IPV4(0),
    /**
     * <code>IPV6 = 1;</code>
     */
    IPV6(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>IPV4 = 0;</code>
     */
    public static final int IPV4_VALUE = 0;
    /**
     * <code>IPV6 = 1;</code>
     */
    public static final int IPV6_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EtherType valueOf(int value) {
      return forNumber(value);
    }

    public static EtherType forNumber(int value) {
      switch (value) {
        case 0: return IPV4;
        case 1: return IPV6;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EtherType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EtherType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EtherType>() {
            public EtherType findValueByNumber(int number) {
              return EtherType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.futurewei.alioth.controller.schema.Common.getDescriptor().getEnumTypes().get(1);
    }

    private static final EtherType[] VALUES = values();

    public static EtherType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EtherType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:aliothcontroller.EtherType)
  }

  /**
   * Protobuf enum {@code aliothcontroller.Protocol}
   */
  public enum Protocol
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TCP = 0;</code>
     */
    TCP(0),
    /**
     * <code>UDP = 1;</code>
     */
    UDP(1),
    /**
     * <code>ICMP = 2;</code>
     */
    ICMP(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TCP = 0;</code>
     */
    public static final int TCP_VALUE = 0;
    /**
     * <code>UDP = 1;</code>
     */
    public static final int UDP_VALUE = 1;
    /**
     * <code>ICMP = 2;</code>
     */
    public static final int ICMP_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Protocol valueOf(int value) {
      return forNumber(value);
    }

    public static Protocol forNumber(int value) {
      switch (value) {
        case 0: return TCP;
        case 1: return UDP;
        case 2: return ICMP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Protocol>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Protocol> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Protocol>() {
            public Protocol findValueByNumber(int number) {
              return Protocol.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.futurewei.alioth.controller.schema.Common.getDescriptor().getEnumTypes().get(2);
    }

    private static final Protocol[] VALUES = values();

    public static Protocol valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Protocol(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:aliothcontroller.Protocol)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\020aliothcontroller*<\n\rOper" +
      "ationType\022\n\n\006CREATE\020\000\022\n\n\006UPDATE\020\001\022\007\n\003GET" +
      "\020\002\022\n\n\006DELETE\020\003*\037\n\tEtherType\022\010\n\004IPV4\020\000\022\010\n" +
      "\004IPV6\020\001*&\n\010Protocol\022\007\n\003TCP\020\000\022\007\n\003UDP\020\001\022\010\n" +
      "\004ICMP\020\002B0\n&com.futurewei.alioth.controll" +
      "er.schemaB\006Commonb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
