// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controlagentservice.proto

package com.futurewei.alioth.controller.schema;

public final class Controlagentservice {
  private Controlagentservice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GoalStateOperationReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aliothcontroller.GoalStateOperationReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
     */
    java.util.List<com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus> 
        getOperationStatusesList();
    /**
     * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
     */
    com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus getOperationStatuses(int index);
    /**
     * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
     */
    int getOperationStatusesCount();
    /**
     * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
     */
    java.util.List<? extends com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatusOrBuilder> 
        getOperationStatusesOrBuilderList();
    /**
     * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
     */
    com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatusOrBuilder getOperationStatusesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code aliothcontroller.GoalStateOperationReply}
   */
  public  static final class GoalStateOperationReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:aliothcontroller.GoalStateOperationReply)
      GoalStateOperationReplyOrBuilder {
    // Use GoalStateOperationReply.newBuilder() to construct.
    private GoalStateOperationReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GoalStateOperationReply() {
      operationStatuses_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GoalStateOperationReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                operationStatuses_ = new java.util.ArrayList<com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus>();
                mutable_bitField0_ |= 0x00000001;
              }
              operationStatuses_.add(
                  input.readMessage(com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          operationStatuses_ = java.util.Collections.unmodifiableList(operationStatuses_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futurewei.alioth.controller.schema.Controlagentservice.internal_static_aliothcontroller_GoalStateOperationReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futurewei.alioth.controller.schema.Controlagentservice.internal_static_aliothcontroller_GoalStateOperationReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.class, com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.Builder.class);
    }

    public interface GoalStateOperationStatusOrBuilder extends
        // @@protoc_insertion_point(interface_extends:aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string resource_id = 1;</code>
       */
      java.lang.String getResourceId();
      /**
       * <code>optional string resource_id = 1;</code>
       */
      com.google.protobuf.ByteString
          getResourceIdBytes();

      /**
       * <code>optional .aliothcontroller.ResourceType resource_type = 2;</code>
       */
      int getResourceTypeValue();
      /**
       * <code>optional .aliothcontroller.ResourceType resource_type = 2;</code>
       */
      com.futurewei.alioth.controller.schema.Common.ResourceType getResourceType();

      /**
       * <code>optional .aliothcontroller.OperationType operation_type = 3;</code>
       */
      int getOperationTypeValue();
      /**
       * <code>optional .aliothcontroller.OperationType operation_type = 3;</code>
       */
      com.futurewei.alioth.controller.schema.Common.OperationType getOperationType();

      /**
       * <code>optional .aliothcontroller.OperationStatus operation_status = 4;</code>
       */
      int getOperationStatusValue();
      /**
       * <code>optional .aliothcontroller.OperationStatus operation_status = 4;</code>
       */
      com.futurewei.alioth.controller.schema.Common.OperationStatus getOperationStatus();
    }
    /**
     * Protobuf type {@code aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus}
     */
    public  static final class GoalStateOperationStatus extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus)
        GoalStateOperationStatusOrBuilder {
      // Use GoalStateOperationStatus.newBuilder() to construct.
      private GoalStateOperationStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private GoalStateOperationStatus() {
        resourceId_ = "";
        resourceType_ = 0;
        operationType_ = 0;
        operationStatus_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private GoalStateOperationStatus(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                resourceId_ = s;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();

                resourceType_ = rawValue;
                break;
              }
              case 24: {
                int rawValue = input.readEnum();

                operationType_ = rawValue;
                break;
              }
              case 32: {
                int rawValue = input.readEnum();

                operationStatus_ = rawValue;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futurewei.alioth.controller.schema.Controlagentservice.internal_static_aliothcontroller_GoalStateOperationReply_GoalStateOperationStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futurewei.alioth.controller.schema.Controlagentservice.internal_static_aliothcontroller_GoalStateOperationReply_GoalStateOperationStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.class, com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.Builder.class);
      }

      public static final int RESOURCE_ID_FIELD_NUMBER = 1;
      private volatile java.lang.Object resourceId_;
      /**
       * <code>optional string resource_id = 1;</code>
       */
      public java.lang.String getResourceId() {
        java.lang.Object ref = resourceId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resourceId_ = s;
          return s;
        }
      }
      /**
       * <code>optional string resource_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResourceIdBytes() {
        java.lang.Object ref = resourceId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resourceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int RESOURCE_TYPE_FIELD_NUMBER = 2;
      private int resourceType_;
      /**
       * <code>optional .aliothcontroller.ResourceType resource_type = 2;</code>
       */
      public int getResourceTypeValue() {
        return resourceType_;
      }
      /**
       * <code>optional .aliothcontroller.ResourceType resource_type = 2;</code>
       */
      public com.futurewei.alioth.controller.schema.Common.ResourceType getResourceType() {
        com.futurewei.alioth.controller.schema.Common.ResourceType result = com.futurewei.alioth.controller.schema.Common.ResourceType.valueOf(resourceType_);
        return result == null ? com.futurewei.alioth.controller.schema.Common.ResourceType.UNRECOGNIZED : result;
      }

      public static final int OPERATION_TYPE_FIELD_NUMBER = 3;
      private int operationType_;
      /**
       * <code>optional .aliothcontroller.OperationType operation_type = 3;</code>
       */
      public int getOperationTypeValue() {
        return operationType_;
      }
      /**
       * <code>optional .aliothcontroller.OperationType operation_type = 3;</code>
       */
      public com.futurewei.alioth.controller.schema.Common.OperationType getOperationType() {
        com.futurewei.alioth.controller.schema.Common.OperationType result = com.futurewei.alioth.controller.schema.Common.OperationType.valueOf(operationType_);
        return result == null ? com.futurewei.alioth.controller.schema.Common.OperationType.UNRECOGNIZED : result;
      }

      public static final int OPERATION_STATUS_FIELD_NUMBER = 4;
      private int operationStatus_;
      /**
       * <code>optional .aliothcontroller.OperationStatus operation_status = 4;</code>
       */
      public int getOperationStatusValue() {
        return operationStatus_;
      }
      /**
       * <code>optional .aliothcontroller.OperationStatus operation_status = 4;</code>
       */
      public com.futurewei.alioth.controller.schema.Common.OperationStatus getOperationStatus() {
        com.futurewei.alioth.controller.schema.Common.OperationStatus result = com.futurewei.alioth.controller.schema.Common.OperationStatus.valueOf(operationStatus_);
        return result == null ? com.futurewei.alioth.controller.schema.Common.OperationStatus.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getResourceIdBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resourceId_);
        }
        if (resourceType_ != com.futurewei.alioth.controller.schema.Common.ResourceType.VPC.getNumber()) {
          output.writeEnum(2, resourceType_);
        }
        if (operationType_ != com.futurewei.alioth.controller.schema.Common.OperationType.CREATE.getNumber()) {
          output.writeEnum(3, operationType_);
        }
        if (operationStatus_ != com.futurewei.alioth.controller.schema.Common.OperationStatus.SUCCESS.getNumber()) {
          output.writeEnum(4, operationStatus_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getResourceIdBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resourceId_);
        }
        if (resourceType_ != com.futurewei.alioth.controller.schema.Common.ResourceType.VPC.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, resourceType_);
        }
        if (operationType_ != com.futurewei.alioth.controller.schema.Common.OperationType.CREATE.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(3, operationType_);
        }
        if (operationStatus_ != com.futurewei.alioth.controller.schema.Common.OperationStatus.SUCCESS.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(4, operationStatus_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus)) {
          return super.equals(obj);
        }
        com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus other = (com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus) obj;

        boolean result = true;
        result = result && getResourceId()
            .equals(other.getResourceId());
        result = result && resourceType_ == other.resourceType_;
        result = result && operationType_ == other.operationType_;
        result = result && operationStatus_ == other.operationStatus_;
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + RESOURCE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getResourceId().hashCode();
        hash = (37 * hash) + RESOURCE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + resourceType_;
        hash = (37 * hash) + OPERATION_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + operationType_;
        hash = (37 * hash) + OPERATION_STATUS_FIELD_NUMBER;
        hash = (53 * hash) + operationStatus_;
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus)
          com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatusOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.futurewei.alioth.controller.schema.Controlagentservice.internal_static_aliothcontroller_GoalStateOperationReply_GoalStateOperationStatus_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.futurewei.alioth.controller.schema.Controlagentservice.internal_static_aliothcontroller_GoalStateOperationReply_GoalStateOperationStatus_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.class, com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.Builder.class);
        }

        // Construct using com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          resourceId_ = "";

          resourceType_ = 0;

          operationType_ = 0;

          operationStatus_ = 0;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.futurewei.alioth.controller.schema.Controlagentservice.internal_static_aliothcontroller_GoalStateOperationReply_GoalStateOperationStatus_descriptor;
        }

        public com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus getDefaultInstanceForType() {
          return com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.getDefaultInstance();
        }

        public com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus build() {
          com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus buildPartial() {
          com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus result = new com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus(this);
          result.resourceId_ = resourceId_;
          result.resourceType_ = resourceType_;
          result.operationType_ = operationType_;
          result.operationStatus_ = operationStatus_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus) {
            return mergeFrom((com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus other) {
          if (other == com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.getDefaultInstance()) return this;
          if (!other.getResourceId().isEmpty()) {
            resourceId_ = other.resourceId_;
            onChanged();
          }
          if (other.resourceType_ != 0) {
            setResourceTypeValue(other.getResourceTypeValue());
          }
          if (other.operationType_ != 0) {
            setOperationTypeValue(other.getOperationTypeValue());
          }
          if (other.operationStatus_ != 0) {
            setOperationStatusValue(other.getOperationStatusValue());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object resourceId_ = "";
        /**
         * <code>optional string resource_id = 1;</code>
         */
        public java.lang.String getResourceId() {
          java.lang.Object ref = resourceId_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            resourceId_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string resource_id = 1;</code>
         */
        public com.google.protobuf.ByteString
            getResourceIdBytes() {
          java.lang.Object ref = resourceId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            resourceId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string resource_id = 1;</code>
         */
        public Builder setResourceId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          resourceId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string resource_id = 1;</code>
         */
        public Builder clearResourceId() {
          
          resourceId_ = getDefaultInstance().getResourceId();
          onChanged();
          return this;
        }
        /**
         * <code>optional string resource_id = 1;</code>
         */
        public Builder setResourceIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          resourceId_ = value;
          onChanged();
          return this;
        }

        private int resourceType_ = 0;
        /**
         * <code>optional .aliothcontroller.ResourceType resource_type = 2;</code>
         */
        public int getResourceTypeValue() {
          return resourceType_;
        }
        /**
         * <code>optional .aliothcontroller.ResourceType resource_type = 2;</code>
         */
        public Builder setResourceTypeValue(int value) {
          resourceType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .aliothcontroller.ResourceType resource_type = 2;</code>
         */
        public com.futurewei.alioth.controller.schema.Common.ResourceType getResourceType() {
          com.futurewei.alioth.controller.schema.Common.ResourceType result = com.futurewei.alioth.controller.schema.Common.ResourceType.valueOf(resourceType_);
          return result == null ? com.futurewei.alioth.controller.schema.Common.ResourceType.UNRECOGNIZED : result;
        }
        /**
         * <code>optional .aliothcontroller.ResourceType resource_type = 2;</code>
         */
        public Builder setResourceType(com.futurewei.alioth.controller.schema.Common.ResourceType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          resourceType_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .aliothcontroller.ResourceType resource_type = 2;</code>
         */
        public Builder clearResourceType() {
          
          resourceType_ = 0;
          onChanged();
          return this;
        }

        private int operationType_ = 0;
        /**
         * <code>optional .aliothcontroller.OperationType operation_type = 3;</code>
         */
        public int getOperationTypeValue() {
          return operationType_;
        }
        /**
         * <code>optional .aliothcontroller.OperationType operation_type = 3;</code>
         */
        public Builder setOperationTypeValue(int value) {
          operationType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .aliothcontroller.OperationType operation_type = 3;</code>
         */
        public com.futurewei.alioth.controller.schema.Common.OperationType getOperationType() {
          com.futurewei.alioth.controller.schema.Common.OperationType result = com.futurewei.alioth.controller.schema.Common.OperationType.valueOf(operationType_);
          return result == null ? com.futurewei.alioth.controller.schema.Common.OperationType.UNRECOGNIZED : result;
        }
        /**
         * <code>optional .aliothcontroller.OperationType operation_type = 3;</code>
         */
        public Builder setOperationType(com.futurewei.alioth.controller.schema.Common.OperationType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          operationType_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .aliothcontroller.OperationType operation_type = 3;</code>
         */
        public Builder clearOperationType() {
          
          operationType_ = 0;
          onChanged();
          return this;
        }

        private int operationStatus_ = 0;
        /**
         * <code>optional .aliothcontroller.OperationStatus operation_status = 4;</code>
         */
        public int getOperationStatusValue() {
          return operationStatus_;
        }
        /**
         * <code>optional .aliothcontroller.OperationStatus operation_status = 4;</code>
         */
        public Builder setOperationStatusValue(int value) {
          operationStatus_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .aliothcontroller.OperationStatus operation_status = 4;</code>
         */
        public com.futurewei.alioth.controller.schema.Common.OperationStatus getOperationStatus() {
          com.futurewei.alioth.controller.schema.Common.OperationStatus result = com.futurewei.alioth.controller.schema.Common.OperationStatus.valueOf(operationStatus_);
          return result == null ? com.futurewei.alioth.controller.schema.Common.OperationStatus.UNRECOGNIZED : result;
        }
        /**
         * <code>optional .aliothcontroller.OperationStatus operation_status = 4;</code>
         */
        public Builder setOperationStatus(com.futurewei.alioth.controller.schema.Common.OperationStatus value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          operationStatus_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .aliothcontroller.OperationStatus operation_status = 4;</code>
         */
        public Builder clearOperationStatus() {
          
          operationStatus_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus)
      }

      // @@protoc_insertion_point(class_scope:aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus)
      private static final com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus();
      }

      public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<GoalStateOperationStatus>
          PARSER = new com.google.protobuf.AbstractParser<GoalStateOperationStatus>() {
        public GoalStateOperationStatus parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new GoalStateOperationStatus(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<GoalStateOperationStatus> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<GoalStateOperationStatus> getParserForType() {
        return PARSER;
      }

      public com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int OPERATION_STATUSES_FIELD_NUMBER = 1;
    private java.util.List<com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus> operationStatuses_;
    /**
     * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
     */
    public java.util.List<com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus> getOperationStatusesList() {
      return operationStatuses_;
    }
    /**
     * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
     */
    public java.util.List<? extends com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatusOrBuilder> 
        getOperationStatusesOrBuilderList() {
      return operationStatuses_;
    }
    /**
     * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
     */
    public int getOperationStatusesCount() {
      return operationStatuses_.size();
    }
    /**
     * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
     */
    public com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus getOperationStatuses(int index) {
      return operationStatuses_.get(index);
    }
    /**
     * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
     */
    public com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatusOrBuilder getOperationStatusesOrBuilder(
        int index) {
      return operationStatuses_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < operationStatuses_.size(); i++) {
        output.writeMessage(1, operationStatuses_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < operationStatuses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, operationStatuses_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply)) {
        return super.equals(obj);
      }
      com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply other = (com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply) obj;

      boolean result = true;
      result = result && getOperationStatusesList()
          .equals(other.getOperationStatusesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getOperationStatusesCount() > 0) {
        hash = (37 * hash) + OPERATION_STATUSES_FIELD_NUMBER;
        hash = (53 * hash) + getOperationStatusesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code aliothcontroller.GoalStateOperationReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:aliothcontroller.GoalStateOperationReply)
        com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futurewei.alioth.controller.schema.Controlagentservice.internal_static_aliothcontroller_GoalStateOperationReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futurewei.alioth.controller.schema.Controlagentservice.internal_static_aliothcontroller_GoalStateOperationReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.class, com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.Builder.class);
      }

      // Construct using com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOperationStatusesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (operationStatusesBuilder_ == null) {
          operationStatuses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          operationStatusesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futurewei.alioth.controller.schema.Controlagentservice.internal_static_aliothcontroller_GoalStateOperationReply_descriptor;
      }

      public com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply getDefaultInstanceForType() {
        return com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.getDefaultInstance();
      }

      public com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply build() {
        com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply buildPartial() {
        com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply result = new com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply(this);
        int from_bitField0_ = bitField0_;
        if (operationStatusesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            operationStatuses_ = java.util.Collections.unmodifiableList(operationStatuses_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.operationStatuses_ = operationStatuses_;
        } else {
          result.operationStatuses_ = operationStatusesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply) {
          return mergeFrom((com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply other) {
        if (other == com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.getDefaultInstance()) return this;
        if (operationStatusesBuilder_ == null) {
          if (!other.operationStatuses_.isEmpty()) {
            if (operationStatuses_.isEmpty()) {
              operationStatuses_ = other.operationStatuses_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOperationStatusesIsMutable();
              operationStatuses_.addAll(other.operationStatuses_);
            }
            onChanged();
          }
        } else {
          if (!other.operationStatuses_.isEmpty()) {
            if (operationStatusesBuilder_.isEmpty()) {
              operationStatusesBuilder_.dispose();
              operationStatusesBuilder_ = null;
              operationStatuses_ = other.operationStatuses_;
              bitField0_ = (bitField0_ & ~0x00000001);
              operationStatusesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOperationStatusesFieldBuilder() : null;
            } else {
              operationStatusesBuilder_.addAllMessages(other.operationStatuses_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus> operationStatuses_ =
        java.util.Collections.emptyList();
      private void ensureOperationStatusesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          operationStatuses_ = new java.util.ArrayList<com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus>(operationStatuses_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus, com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.Builder, com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatusOrBuilder> operationStatusesBuilder_;

      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public java.util.List<com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus> getOperationStatusesList() {
        if (operationStatusesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(operationStatuses_);
        } else {
          return operationStatusesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public int getOperationStatusesCount() {
        if (operationStatusesBuilder_ == null) {
          return operationStatuses_.size();
        } else {
          return operationStatusesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus getOperationStatuses(int index) {
        if (operationStatusesBuilder_ == null) {
          return operationStatuses_.get(index);
        } else {
          return operationStatusesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public Builder setOperationStatuses(
          int index, com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus value) {
        if (operationStatusesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOperationStatusesIsMutable();
          operationStatuses_.set(index, value);
          onChanged();
        } else {
          operationStatusesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public Builder setOperationStatuses(
          int index, com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.Builder builderForValue) {
        if (operationStatusesBuilder_ == null) {
          ensureOperationStatusesIsMutable();
          operationStatuses_.set(index, builderForValue.build());
          onChanged();
        } else {
          operationStatusesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public Builder addOperationStatuses(com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus value) {
        if (operationStatusesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOperationStatusesIsMutable();
          operationStatuses_.add(value);
          onChanged();
        } else {
          operationStatusesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public Builder addOperationStatuses(
          int index, com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus value) {
        if (operationStatusesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOperationStatusesIsMutable();
          operationStatuses_.add(index, value);
          onChanged();
        } else {
          operationStatusesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public Builder addOperationStatuses(
          com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.Builder builderForValue) {
        if (operationStatusesBuilder_ == null) {
          ensureOperationStatusesIsMutable();
          operationStatuses_.add(builderForValue.build());
          onChanged();
        } else {
          operationStatusesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public Builder addOperationStatuses(
          int index, com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.Builder builderForValue) {
        if (operationStatusesBuilder_ == null) {
          ensureOperationStatusesIsMutable();
          operationStatuses_.add(index, builderForValue.build());
          onChanged();
        } else {
          operationStatusesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public Builder addAllOperationStatuses(
          java.lang.Iterable<? extends com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus> values) {
        if (operationStatusesBuilder_ == null) {
          ensureOperationStatusesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, operationStatuses_);
          onChanged();
        } else {
          operationStatusesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public Builder clearOperationStatuses() {
        if (operationStatusesBuilder_ == null) {
          operationStatuses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          operationStatusesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public Builder removeOperationStatuses(int index) {
        if (operationStatusesBuilder_ == null) {
          ensureOperationStatusesIsMutable();
          operationStatuses_.remove(index);
          onChanged();
        } else {
          operationStatusesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.Builder getOperationStatusesBuilder(
          int index) {
        return getOperationStatusesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatusOrBuilder getOperationStatusesOrBuilder(
          int index) {
        if (operationStatusesBuilder_ == null) {
          return operationStatuses_.get(index);  } else {
          return operationStatusesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public java.util.List<? extends com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatusOrBuilder> 
           getOperationStatusesOrBuilderList() {
        if (operationStatusesBuilder_ != null) {
          return operationStatusesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(operationStatuses_);
        }
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.Builder addOperationStatusesBuilder() {
        return getOperationStatusesFieldBuilder().addBuilder(
            com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.Builder addOperationStatusesBuilder(
          int index) {
        return getOperationStatusesFieldBuilder().addBuilder(
            index, com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .aliothcontroller.GoalStateOperationReply.GoalStateOperationStatus operation_statuses = 1;</code>
       */
      public java.util.List<com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.Builder> 
           getOperationStatusesBuilderList() {
        return getOperationStatusesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus, com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.Builder, com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatusOrBuilder> 
          getOperationStatusesFieldBuilder() {
        if (operationStatusesBuilder_ == null) {
          operationStatusesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus, com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatus.Builder, com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply.GoalStateOperationStatusOrBuilder>(
                  operationStatuses_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          operationStatuses_ = null;
        }
        return operationStatusesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:aliothcontroller.GoalStateOperationReply)
    }

    // @@protoc_insertion_point(class_scope:aliothcontroller.GoalStateOperationReply)
    private static final com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply();
    }

    public static com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GoalStateOperationReply>
        PARSER = new com.google.protobuf.AbstractParser<GoalStateOperationReply>() {
      public GoalStateOperationReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GoalStateOperationReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GoalStateOperationReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GoalStateOperationReply> getParserForType() {
      return PARSER;
    }

    public com.futurewei.alioth.controller.schema.Controlagentservice.GoalStateOperationReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aliothcontroller_GoalStateOperationReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aliothcontroller_GoalStateOperationReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aliothcontroller_GoalStateOperationReply_GoalStateOperationStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aliothcontroller_GoalStateOperationReply_GoalStateOperationStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031controlagentservice.proto\022\020aliothcontr" +
      "oller\032\014common.proto\032\017goalstate.proto\"\330\002\n" +
      "\027GoalStateOperationReply\022^\n\022operation_st" +
      "atuses\030\001 \003(\0132B.aliothcontroller.GoalStat" +
      "eOperationReply.GoalStateOperationStatus" +
      "\032\334\001\n\030GoalStateOperationStatus\022\023\n\013resourc" +
      "e_id\030\001 \001(\t\0225\n\rresource_type\030\002 \001(\0162\036.alio" +
      "thcontroller.ResourceType\0227\n\016operation_t" +
      "ype\030\003 \001(\0162\037.aliothcontroller.OperationTy" +
      "pe\022;\n\020operation_status\030\004 \001(\0162!.aliothcon",
      "troller.OperationStatus2y\n\023ControlAgentS" +
      "ervice\022b\n\026ModifyNetworkResources\022\033.aliot" +
      "hcontroller.GoalState\032).aliothcontroller" +
      ".GoalStateOperationReply\"\000B(\n&com.future" +
      "wei.alioth.controller.schemab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.futurewei.alioth.controller.schema.Common.getDescriptor(),
          com.futurewei.alioth.controller.schema.Goalstate.getDescriptor(),
        }, assigner);
    internal_static_aliothcontroller_GoalStateOperationReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aliothcontroller_GoalStateOperationReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aliothcontroller_GoalStateOperationReply_descriptor,
        new java.lang.String[] { "OperationStatuses", });
    internal_static_aliothcontroller_GoalStateOperationReply_GoalStateOperationStatus_descriptor =
      internal_static_aliothcontroller_GoalStateOperationReply_descriptor.getNestedTypes().get(0);
    internal_static_aliothcontroller_GoalStateOperationReply_GoalStateOperationStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aliothcontroller_GoalStateOperationReply_GoalStateOperationStatus_descriptor,
        new java.lang.String[] { "ResourceId", "ResourceType", "OperationType", "OperationStatus", });
    com.futurewei.alioth.controller.schema.Common.getDescriptor();
    com.futurewei.alioth.controller.schema.Goalstate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
