// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: goalstate.proto

package com.futurewei.alioth.controller.schema;

public final class Goalstate {
  private Goalstate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GoalStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aliothcontroller.GoalState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
     */
    java.util.List<com.futurewei.alioth.controller.schema.Vpc.VpcState> 
        getVpcStatesList();
    /**
     * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
     */
    com.futurewei.alioth.controller.schema.Vpc.VpcState getVpcStates(int index);
    /**
     * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
     */
    int getVpcStatesCount();
    /**
     * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
     */
    java.util.List<? extends com.futurewei.alioth.controller.schema.Vpc.VpcStateOrBuilder> 
        getVpcStatesOrBuilderList();
    /**
     * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
     */
    com.futurewei.alioth.controller.schema.Vpc.VpcStateOrBuilder getVpcStatesOrBuilder(
        int index);

    /**
     * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
     */
    java.util.List<com.futurewei.alioth.controller.schema.Subnet.SubnetState> 
        getSubnetStatesList();
    /**
     * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
     */
    com.futurewei.alioth.controller.schema.Subnet.SubnetState getSubnetStates(int index);
    /**
     * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
     */
    int getSubnetStatesCount();
    /**
     * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
     */
    java.util.List<? extends com.futurewei.alioth.controller.schema.Subnet.SubnetStateOrBuilder> 
        getSubnetStatesOrBuilderList();
    /**
     * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
     */
    com.futurewei.alioth.controller.schema.Subnet.SubnetStateOrBuilder getSubnetStatesOrBuilder(
        int index);

    /**
     * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
     */
    java.util.List<com.futurewei.alioth.controller.schema.Port.PortState> 
        getPortStatesList();
    /**
     * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
     */
    com.futurewei.alioth.controller.schema.Port.PortState getPortStates(int index);
    /**
     * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
     */
    int getPortStatesCount();
    /**
     * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
     */
    java.util.List<? extends com.futurewei.alioth.controller.schema.Port.PortStateOrBuilder> 
        getPortStatesOrBuilderList();
    /**
     * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
     */
    com.futurewei.alioth.controller.schema.Port.PortStateOrBuilder getPortStatesOrBuilder(
        int index);

    /**
     * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
     */
    java.util.List<com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState> 
        getSecurityGroupStatesList();
    /**
     * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
     */
    com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState getSecurityGroupStates(int index);
    /**
     * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
     */
    int getSecurityGroupStatesCount();
    /**
     * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
     */
    java.util.List<? extends com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupStateOrBuilder> 
        getSecurityGroupStatesOrBuilderList();
    /**
     * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
     */
    com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupStateOrBuilder getSecurityGroupStatesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code aliothcontroller.GoalState}
   */
  public  static final class GoalState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:aliothcontroller.GoalState)
      GoalStateOrBuilder {
    // Use GoalState.newBuilder() to construct.
    private GoalState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GoalState() {
      vpcStates_ = java.util.Collections.emptyList();
      subnetStates_ = java.util.Collections.emptyList();
      portStates_ = java.util.Collections.emptyList();
      securityGroupStates_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GoalState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                vpcStates_ = new java.util.ArrayList<com.futurewei.alioth.controller.schema.Vpc.VpcState>();
                mutable_bitField0_ |= 0x00000001;
              }
              vpcStates_.add(
                  input.readMessage(com.futurewei.alioth.controller.schema.Vpc.VpcState.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                subnetStates_ = new java.util.ArrayList<com.futurewei.alioth.controller.schema.Subnet.SubnetState>();
                mutable_bitField0_ |= 0x00000002;
              }
              subnetStates_.add(
                  input.readMessage(com.futurewei.alioth.controller.schema.Subnet.SubnetState.parser(), extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                portStates_ = new java.util.ArrayList<com.futurewei.alioth.controller.schema.Port.PortState>();
                mutable_bitField0_ |= 0x00000004;
              }
              portStates_.add(
                  input.readMessage(com.futurewei.alioth.controller.schema.Port.PortState.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                securityGroupStates_ = new java.util.ArrayList<com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState>();
                mutable_bitField0_ |= 0x00000008;
              }
              securityGroupStates_.add(
                  input.readMessage(com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          vpcStates_ = java.util.Collections.unmodifiableList(vpcStates_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          subnetStates_ = java.util.Collections.unmodifiableList(subnetStates_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          portStates_ = java.util.Collections.unmodifiableList(portStates_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          securityGroupStates_ = java.util.Collections.unmodifiableList(securityGroupStates_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futurewei.alioth.controller.schema.Goalstate.internal_static_aliothcontroller_GoalState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futurewei.alioth.controller.schema.Goalstate.internal_static_aliothcontroller_GoalState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futurewei.alioth.controller.schema.Goalstate.GoalState.class, com.futurewei.alioth.controller.schema.Goalstate.GoalState.Builder.class);
    }

    public static final int VPC_STATES_FIELD_NUMBER = 1;
    private java.util.List<com.futurewei.alioth.controller.schema.Vpc.VpcState> vpcStates_;
    /**
     * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
     */
    public java.util.List<com.futurewei.alioth.controller.schema.Vpc.VpcState> getVpcStatesList() {
      return vpcStates_;
    }
    /**
     * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
     */
    public java.util.List<? extends com.futurewei.alioth.controller.schema.Vpc.VpcStateOrBuilder> 
        getVpcStatesOrBuilderList() {
      return vpcStates_;
    }
    /**
     * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
     */
    public int getVpcStatesCount() {
      return vpcStates_.size();
    }
    /**
     * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
     */
    public com.futurewei.alioth.controller.schema.Vpc.VpcState getVpcStates(int index) {
      return vpcStates_.get(index);
    }
    /**
     * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
     */
    public com.futurewei.alioth.controller.schema.Vpc.VpcStateOrBuilder getVpcStatesOrBuilder(
        int index) {
      return vpcStates_.get(index);
    }

    public static final int SUBNET_STATES_FIELD_NUMBER = 2;
    private java.util.List<com.futurewei.alioth.controller.schema.Subnet.SubnetState> subnetStates_;
    /**
     * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
     */
    public java.util.List<com.futurewei.alioth.controller.schema.Subnet.SubnetState> getSubnetStatesList() {
      return subnetStates_;
    }
    /**
     * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
     */
    public java.util.List<? extends com.futurewei.alioth.controller.schema.Subnet.SubnetStateOrBuilder> 
        getSubnetStatesOrBuilderList() {
      return subnetStates_;
    }
    /**
     * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
     */
    public int getSubnetStatesCount() {
      return subnetStates_.size();
    }
    /**
     * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
     */
    public com.futurewei.alioth.controller.schema.Subnet.SubnetState getSubnetStates(int index) {
      return subnetStates_.get(index);
    }
    /**
     * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
     */
    public com.futurewei.alioth.controller.schema.Subnet.SubnetStateOrBuilder getSubnetStatesOrBuilder(
        int index) {
      return subnetStates_.get(index);
    }

    public static final int PORT_STATES_FIELD_NUMBER = 3;
    private java.util.List<com.futurewei.alioth.controller.schema.Port.PortState> portStates_;
    /**
     * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
     */
    public java.util.List<com.futurewei.alioth.controller.schema.Port.PortState> getPortStatesList() {
      return portStates_;
    }
    /**
     * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
     */
    public java.util.List<? extends com.futurewei.alioth.controller.schema.Port.PortStateOrBuilder> 
        getPortStatesOrBuilderList() {
      return portStates_;
    }
    /**
     * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
     */
    public int getPortStatesCount() {
      return portStates_.size();
    }
    /**
     * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
     */
    public com.futurewei.alioth.controller.schema.Port.PortState getPortStates(int index) {
      return portStates_.get(index);
    }
    /**
     * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
     */
    public com.futurewei.alioth.controller.schema.Port.PortStateOrBuilder getPortStatesOrBuilder(
        int index) {
      return portStates_.get(index);
    }

    public static final int SECURITY_GROUP_STATES_FIELD_NUMBER = 4;
    private java.util.List<com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState> securityGroupStates_;
    /**
     * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
     */
    public java.util.List<com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState> getSecurityGroupStatesList() {
      return securityGroupStates_;
    }
    /**
     * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
     */
    public java.util.List<? extends com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupStateOrBuilder> 
        getSecurityGroupStatesOrBuilderList() {
      return securityGroupStates_;
    }
    /**
     * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
     */
    public int getSecurityGroupStatesCount() {
      return securityGroupStates_.size();
    }
    /**
     * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
     */
    public com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState getSecurityGroupStates(int index) {
      return securityGroupStates_.get(index);
    }
    /**
     * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
     */
    public com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupStateOrBuilder getSecurityGroupStatesOrBuilder(
        int index) {
      return securityGroupStates_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < vpcStates_.size(); i++) {
        output.writeMessage(1, vpcStates_.get(i));
      }
      for (int i = 0; i < subnetStates_.size(); i++) {
        output.writeMessage(2, subnetStates_.get(i));
      }
      for (int i = 0; i < portStates_.size(); i++) {
        output.writeMessage(3, portStates_.get(i));
      }
      for (int i = 0; i < securityGroupStates_.size(); i++) {
        output.writeMessage(4, securityGroupStates_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < vpcStates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, vpcStates_.get(i));
      }
      for (int i = 0; i < subnetStates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, subnetStates_.get(i));
      }
      for (int i = 0; i < portStates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, portStates_.get(i));
      }
      for (int i = 0; i < securityGroupStates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, securityGroupStates_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.futurewei.alioth.controller.schema.Goalstate.GoalState)) {
        return super.equals(obj);
      }
      com.futurewei.alioth.controller.schema.Goalstate.GoalState other = (com.futurewei.alioth.controller.schema.Goalstate.GoalState) obj;

      boolean result = true;
      result = result && getVpcStatesList()
          .equals(other.getVpcStatesList());
      result = result && getSubnetStatesList()
          .equals(other.getSubnetStatesList());
      result = result && getPortStatesList()
          .equals(other.getPortStatesList());
      result = result && getSecurityGroupStatesList()
          .equals(other.getSecurityGroupStatesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getVpcStatesCount() > 0) {
        hash = (37 * hash) + VPC_STATES_FIELD_NUMBER;
        hash = (53 * hash) + getVpcStatesList().hashCode();
      }
      if (getSubnetStatesCount() > 0) {
        hash = (37 * hash) + SUBNET_STATES_FIELD_NUMBER;
        hash = (53 * hash) + getSubnetStatesList().hashCode();
      }
      if (getPortStatesCount() > 0) {
        hash = (37 * hash) + PORT_STATES_FIELD_NUMBER;
        hash = (53 * hash) + getPortStatesList().hashCode();
      }
      if (getSecurityGroupStatesCount() > 0) {
        hash = (37 * hash) + SECURITY_GROUP_STATES_FIELD_NUMBER;
        hash = (53 * hash) + getSecurityGroupStatesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.futurewei.alioth.controller.schema.Goalstate.GoalState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futurewei.alioth.controller.schema.Goalstate.GoalState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futurewei.alioth.controller.schema.Goalstate.GoalState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futurewei.alioth.controller.schema.Goalstate.GoalState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futurewei.alioth.controller.schema.Goalstate.GoalState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futurewei.alioth.controller.schema.Goalstate.GoalState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futurewei.alioth.controller.schema.Goalstate.GoalState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.futurewei.alioth.controller.schema.Goalstate.GoalState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futurewei.alioth.controller.schema.Goalstate.GoalState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futurewei.alioth.controller.schema.Goalstate.GoalState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.futurewei.alioth.controller.schema.Goalstate.GoalState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code aliothcontroller.GoalState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:aliothcontroller.GoalState)
        com.futurewei.alioth.controller.schema.Goalstate.GoalStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futurewei.alioth.controller.schema.Goalstate.internal_static_aliothcontroller_GoalState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futurewei.alioth.controller.schema.Goalstate.internal_static_aliothcontroller_GoalState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futurewei.alioth.controller.schema.Goalstate.GoalState.class, com.futurewei.alioth.controller.schema.Goalstate.GoalState.Builder.class);
      }

      // Construct using com.futurewei.alioth.controller.schema.Goalstate.GoalState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getVpcStatesFieldBuilder();
          getSubnetStatesFieldBuilder();
          getPortStatesFieldBuilder();
          getSecurityGroupStatesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (vpcStatesBuilder_ == null) {
          vpcStates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          vpcStatesBuilder_.clear();
        }
        if (subnetStatesBuilder_ == null) {
          subnetStates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          subnetStatesBuilder_.clear();
        }
        if (portStatesBuilder_ == null) {
          portStates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          portStatesBuilder_.clear();
        }
        if (securityGroupStatesBuilder_ == null) {
          securityGroupStates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          securityGroupStatesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futurewei.alioth.controller.schema.Goalstate.internal_static_aliothcontroller_GoalState_descriptor;
      }

      public com.futurewei.alioth.controller.schema.Goalstate.GoalState getDefaultInstanceForType() {
        return com.futurewei.alioth.controller.schema.Goalstate.GoalState.getDefaultInstance();
      }

      public com.futurewei.alioth.controller.schema.Goalstate.GoalState build() {
        com.futurewei.alioth.controller.schema.Goalstate.GoalState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futurewei.alioth.controller.schema.Goalstate.GoalState buildPartial() {
        com.futurewei.alioth.controller.schema.Goalstate.GoalState result = new com.futurewei.alioth.controller.schema.Goalstate.GoalState(this);
        int from_bitField0_ = bitField0_;
        if (vpcStatesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            vpcStates_ = java.util.Collections.unmodifiableList(vpcStates_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.vpcStates_ = vpcStates_;
        } else {
          result.vpcStates_ = vpcStatesBuilder_.build();
        }
        if (subnetStatesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            subnetStates_ = java.util.Collections.unmodifiableList(subnetStates_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.subnetStates_ = subnetStates_;
        } else {
          result.subnetStates_ = subnetStatesBuilder_.build();
        }
        if (portStatesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            portStates_ = java.util.Collections.unmodifiableList(portStates_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.portStates_ = portStates_;
        } else {
          result.portStates_ = portStatesBuilder_.build();
        }
        if (securityGroupStatesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            securityGroupStates_ = java.util.Collections.unmodifiableList(securityGroupStates_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.securityGroupStates_ = securityGroupStates_;
        } else {
          result.securityGroupStates_ = securityGroupStatesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futurewei.alioth.controller.schema.Goalstate.GoalState) {
          return mergeFrom((com.futurewei.alioth.controller.schema.Goalstate.GoalState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futurewei.alioth.controller.schema.Goalstate.GoalState other) {
        if (other == com.futurewei.alioth.controller.schema.Goalstate.GoalState.getDefaultInstance()) return this;
        if (vpcStatesBuilder_ == null) {
          if (!other.vpcStates_.isEmpty()) {
            if (vpcStates_.isEmpty()) {
              vpcStates_ = other.vpcStates_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureVpcStatesIsMutable();
              vpcStates_.addAll(other.vpcStates_);
            }
            onChanged();
          }
        } else {
          if (!other.vpcStates_.isEmpty()) {
            if (vpcStatesBuilder_.isEmpty()) {
              vpcStatesBuilder_.dispose();
              vpcStatesBuilder_ = null;
              vpcStates_ = other.vpcStates_;
              bitField0_ = (bitField0_ & ~0x00000001);
              vpcStatesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getVpcStatesFieldBuilder() : null;
            } else {
              vpcStatesBuilder_.addAllMessages(other.vpcStates_);
            }
          }
        }
        if (subnetStatesBuilder_ == null) {
          if (!other.subnetStates_.isEmpty()) {
            if (subnetStates_.isEmpty()) {
              subnetStates_ = other.subnetStates_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSubnetStatesIsMutable();
              subnetStates_.addAll(other.subnetStates_);
            }
            onChanged();
          }
        } else {
          if (!other.subnetStates_.isEmpty()) {
            if (subnetStatesBuilder_.isEmpty()) {
              subnetStatesBuilder_.dispose();
              subnetStatesBuilder_ = null;
              subnetStates_ = other.subnetStates_;
              bitField0_ = (bitField0_ & ~0x00000002);
              subnetStatesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSubnetStatesFieldBuilder() : null;
            } else {
              subnetStatesBuilder_.addAllMessages(other.subnetStates_);
            }
          }
        }
        if (portStatesBuilder_ == null) {
          if (!other.portStates_.isEmpty()) {
            if (portStates_.isEmpty()) {
              portStates_ = other.portStates_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePortStatesIsMutable();
              portStates_.addAll(other.portStates_);
            }
            onChanged();
          }
        } else {
          if (!other.portStates_.isEmpty()) {
            if (portStatesBuilder_.isEmpty()) {
              portStatesBuilder_.dispose();
              portStatesBuilder_ = null;
              portStates_ = other.portStates_;
              bitField0_ = (bitField0_ & ~0x00000004);
              portStatesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPortStatesFieldBuilder() : null;
            } else {
              portStatesBuilder_.addAllMessages(other.portStates_);
            }
          }
        }
        if (securityGroupStatesBuilder_ == null) {
          if (!other.securityGroupStates_.isEmpty()) {
            if (securityGroupStates_.isEmpty()) {
              securityGroupStates_ = other.securityGroupStates_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureSecurityGroupStatesIsMutable();
              securityGroupStates_.addAll(other.securityGroupStates_);
            }
            onChanged();
          }
        } else {
          if (!other.securityGroupStates_.isEmpty()) {
            if (securityGroupStatesBuilder_.isEmpty()) {
              securityGroupStatesBuilder_.dispose();
              securityGroupStatesBuilder_ = null;
              securityGroupStates_ = other.securityGroupStates_;
              bitField0_ = (bitField0_ & ~0x00000008);
              securityGroupStatesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSecurityGroupStatesFieldBuilder() : null;
            } else {
              securityGroupStatesBuilder_.addAllMessages(other.securityGroupStates_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futurewei.alioth.controller.schema.Goalstate.GoalState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futurewei.alioth.controller.schema.Goalstate.GoalState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.futurewei.alioth.controller.schema.Vpc.VpcState> vpcStates_ =
        java.util.Collections.emptyList();
      private void ensureVpcStatesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          vpcStates_ = new java.util.ArrayList<com.futurewei.alioth.controller.schema.Vpc.VpcState>(vpcStates_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.futurewei.alioth.controller.schema.Vpc.VpcState, com.futurewei.alioth.controller.schema.Vpc.VpcState.Builder, com.futurewei.alioth.controller.schema.Vpc.VpcStateOrBuilder> vpcStatesBuilder_;

      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public java.util.List<com.futurewei.alioth.controller.schema.Vpc.VpcState> getVpcStatesList() {
        if (vpcStatesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(vpcStates_);
        } else {
          return vpcStatesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public int getVpcStatesCount() {
        if (vpcStatesBuilder_ == null) {
          return vpcStates_.size();
        } else {
          return vpcStatesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public com.futurewei.alioth.controller.schema.Vpc.VpcState getVpcStates(int index) {
        if (vpcStatesBuilder_ == null) {
          return vpcStates_.get(index);
        } else {
          return vpcStatesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public Builder setVpcStates(
          int index, com.futurewei.alioth.controller.schema.Vpc.VpcState value) {
        if (vpcStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVpcStatesIsMutable();
          vpcStates_.set(index, value);
          onChanged();
        } else {
          vpcStatesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public Builder setVpcStates(
          int index, com.futurewei.alioth.controller.schema.Vpc.VpcState.Builder builderForValue) {
        if (vpcStatesBuilder_ == null) {
          ensureVpcStatesIsMutable();
          vpcStates_.set(index, builderForValue.build());
          onChanged();
        } else {
          vpcStatesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public Builder addVpcStates(com.futurewei.alioth.controller.schema.Vpc.VpcState value) {
        if (vpcStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVpcStatesIsMutable();
          vpcStates_.add(value);
          onChanged();
        } else {
          vpcStatesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public Builder addVpcStates(
          int index, com.futurewei.alioth.controller.schema.Vpc.VpcState value) {
        if (vpcStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVpcStatesIsMutable();
          vpcStates_.add(index, value);
          onChanged();
        } else {
          vpcStatesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public Builder addVpcStates(
          com.futurewei.alioth.controller.schema.Vpc.VpcState.Builder builderForValue) {
        if (vpcStatesBuilder_ == null) {
          ensureVpcStatesIsMutable();
          vpcStates_.add(builderForValue.build());
          onChanged();
        } else {
          vpcStatesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public Builder addVpcStates(
          int index, com.futurewei.alioth.controller.schema.Vpc.VpcState.Builder builderForValue) {
        if (vpcStatesBuilder_ == null) {
          ensureVpcStatesIsMutable();
          vpcStates_.add(index, builderForValue.build());
          onChanged();
        } else {
          vpcStatesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public Builder addAllVpcStates(
          java.lang.Iterable<? extends com.futurewei.alioth.controller.schema.Vpc.VpcState> values) {
        if (vpcStatesBuilder_ == null) {
          ensureVpcStatesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, vpcStates_);
          onChanged();
        } else {
          vpcStatesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public Builder clearVpcStates() {
        if (vpcStatesBuilder_ == null) {
          vpcStates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          vpcStatesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public Builder removeVpcStates(int index) {
        if (vpcStatesBuilder_ == null) {
          ensureVpcStatesIsMutable();
          vpcStates_.remove(index);
          onChanged();
        } else {
          vpcStatesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public com.futurewei.alioth.controller.schema.Vpc.VpcState.Builder getVpcStatesBuilder(
          int index) {
        return getVpcStatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public com.futurewei.alioth.controller.schema.Vpc.VpcStateOrBuilder getVpcStatesOrBuilder(
          int index) {
        if (vpcStatesBuilder_ == null) {
          return vpcStates_.get(index);  } else {
          return vpcStatesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public java.util.List<? extends com.futurewei.alioth.controller.schema.Vpc.VpcStateOrBuilder> 
           getVpcStatesOrBuilderList() {
        if (vpcStatesBuilder_ != null) {
          return vpcStatesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(vpcStates_);
        }
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public com.futurewei.alioth.controller.schema.Vpc.VpcState.Builder addVpcStatesBuilder() {
        return getVpcStatesFieldBuilder().addBuilder(
            com.futurewei.alioth.controller.schema.Vpc.VpcState.getDefaultInstance());
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public com.futurewei.alioth.controller.schema.Vpc.VpcState.Builder addVpcStatesBuilder(
          int index) {
        return getVpcStatesFieldBuilder().addBuilder(
            index, com.futurewei.alioth.controller.schema.Vpc.VpcState.getDefaultInstance());
      }
      /**
       * <code>repeated .aliothcontroller.VpcState vpc_states = 1;</code>
       */
      public java.util.List<com.futurewei.alioth.controller.schema.Vpc.VpcState.Builder> 
           getVpcStatesBuilderList() {
        return getVpcStatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.futurewei.alioth.controller.schema.Vpc.VpcState, com.futurewei.alioth.controller.schema.Vpc.VpcState.Builder, com.futurewei.alioth.controller.schema.Vpc.VpcStateOrBuilder> 
          getVpcStatesFieldBuilder() {
        if (vpcStatesBuilder_ == null) {
          vpcStatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.futurewei.alioth.controller.schema.Vpc.VpcState, com.futurewei.alioth.controller.schema.Vpc.VpcState.Builder, com.futurewei.alioth.controller.schema.Vpc.VpcStateOrBuilder>(
                  vpcStates_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          vpcStates_ = null;
        }
        return vpcStatesBuilder_;
      }

      private java.util.List<com.futurewei.alioth.controller.schema.Subnet.SubnetState> subnetStates_ =
        java.util.Collections.emptyList();
      private void ensureSubnetStatesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          subnetStates_ = new java.util.ArrayList<com.futurewei.alioth.controller.schema.Subnet.SubnetState>(subnetStates_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.futurewei.alioth.controller.schema.Subnet.SubnetState, com.futurewei.alioth.controller.schema.Subnet.SubnetState.Builder, com.futurewei.alioth.controller.schema.Subnet.SubnetStateOrBuilder> subnetStatesBuilder_;

      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public java.util.List<com.futurewei.alioth.controller.schema.Subnet.SubnetState> getSubnetStatesList() {
        if (subnetStatesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(subnetStates_);
        } else {
          return subnetStatesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public int getSubnetStatesCount() {
        if (subnetStatesBuilder_ == null) {
          return subnetStates_.size();
        } else {
          return subnetStatesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public com.futurewei.alioth.controller.schema.Subnet.SubnetState getSubnetStates(int index) {
        if (subnetStatesBuilder_ == null) {
          return subnetStates_.get(index);
        } else {
          return subnetStatesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public Builder setSubnetStates(
          int index, com.futurewei.alioth.controller.schema.Subnet.SubnetState value) {
        if (subnetStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubnetStatesIsMutable();
          subnetStates_.set(index, value);
          onChanged();
        } else {
          subnetStatesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public Builder setSubnetStates(
          int index, com.futurewei.alioth.controller.schema.Subnet.SubnetState.Builder builderForValue) {
        if (subnetStatesBuilder_ == null) {
          ensureSubnetStatesIsMutable();
          subnetStates_.set(index, builderForValue.build());
          onChanged();
        } else {
          subnetStatesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public Builder addSubnetStates(com.futurewei.alioth.controller.schema.Subnet.SubnetState value) {
        if (subnetStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubnetStatesIsMutable();
          subnetStates_.add(value);
          onChanged();
        } else {
          subnetStatesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public Builder addSubnetStates(
          int index, com.futurewei.alioth.controller.schema.Subnet.SubnetState value) {
        if (subnetStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubnetStatesIsMutable();
          subnetStates_.add(index, value);
          onChanged();
        } else {
          subnetStatesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public Builder addSubnetStates(
          com.futurewei.alioth.controller.schema.Subnet.SubnetState.Builder builderForValue) {
        if (subnetStatesBuilder_ == null) {
          ensureSubnetStatesIsMutable();
          subnetStates_.add(builderForValue.build());
          onChanged();
        } else {
          subnetStatesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public Builder addSubnetStates(
          int index, com.futurewei.alioth.controller.schema.Subnet.SubnetState.Builder builderForValue) {
        if (subnetStatesBuilder_ == null) {
          ensureSubnetStatesIsMutable();
          subnetStates_.add(index, builderForValue.build());
          onChanged();
        } else {
          subnetStatesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public Builder addAllSubnetStates(
          java.lang.Iterable<? extends com.futurewei.alioth.controller.schema.Subnet.SubnetState> values) {
        if (subnetStatesBuilder_ == null) {
          ensureSubnetStatesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, subnetStates_);
          onChanged();
        } else {
          subnetStatesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public Builder clearSubnetStates() {
        if (subnetStatesBuilder_ == null) {
          subnetStates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          subnetStatesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public Builder removeSubnetStates(int index) {
        if (subnetStatesBuilder_ == null) {
          ensureSubnetStatesIsMutable();
          subnetStates_.remove(index);
          onChanged();
        } else {
          subnetStatesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public com.futurewei.alioth.controller.schema.Subnet.SubnetState.Builder getSubnetStatesBuilder(
          int index) {
        return getSubnetStatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public com.futurewei.alioth.controller.schema.Subnet.SubnetStateOrBuilder getSubnetStatesOrBuilder(
          int index) {
        if (subnetStatesBuilder_ == null) {
          return subnetStates_.get(index);  } else {
          return subnetStatesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public java.util.List<? extends com.futurewei.alioth.controller.schema.Subnet.SubnetStateOrBuilder> 
           getSubnetStatesOrBuilderList() {
        if (subnetStatesBuilder_ != null) {
          return subnetStatesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(subnetStates_);
        }
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public com.futurewei.alioth.controller.schema.Subnet.SubnetState.Builder addSubnetStatesBuilder() {
        return getSubnetStatesFieldBuilder().addBuilder(
            com.futurewei.alioth.controller.schema.Subnet.SubnetState.getDefaultInstance());
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public com.futurewei.alioth.controller.schema.Subnet.SubnetState.Builder addSubnetStatesBuilder(
          int index) {
        return getSubnetStatesFieldBuilder().addBuilder(
            index, com.futurewei.alioth.controller.schema.Subnet.SubnetState.getDefaultInstance());
      }
      /**
       * <code>repeated .aliothcontroller.SubnetState subnet_states = 2;</code>
       */
      public java.util.List<com.futurewei.alioth.controller.schema.Subnet.SubnetState.Builder> 
           getSubnetStatesBuilderList() {
        return getSubnetStatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.futurewei.alioth.controller.schema.Subnet.SubnetState, com.futurewei.alioth.controller.schema.Subnet.SubnetState.Builder, com.futurewei.alioth.controller.schema.Subnet.SubnetStateOrBuilder> 
          getSubnetStatesFieldBuilder() {
        if (subnetStatesBuilder_ == null) {
          subnetStatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.futurewei.alioth.controller.schema.Subnet.SubnetState, com.futurewei.alioth.controller.schema.Subnet.SubnetState.Builder, com.futurewei.alioth.controller.schema.Subnet.SubnetStateOrBuilder>(
                  subnetStates_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          subnetStates_ = null;
        }
        return subnetStatesBuilder_;
      }

      private java.util.List<com.futurewei.alioth.controller.schema.Port.PortState> portStates_ =
        java.util.Collections.emptyList();
      private void ensurePortStatesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          portStates_ = new java.util.ArrayList<com.futurewei.alioth.controller.schema.Port.PortState>(portStates_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.futurewei.alioth.controller.schema.Port.PortState, com.futurewei.alioth.controller.schema.Port.PortState.Builder, com.futurewei.alioth.controller.schema.Port.PortStateOrBuilder> portStatesBuilder_;

      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public java.util.List<com.futurewei.alioth.controller.schema.Port.PortState> getPortStatesList() {
        if (portStatesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(portStates_);
        } else {
          return portStatesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public int getPortStatesCount() {
        if (portStatesBuilder_ == null) {
          return portStates_.size();
        } else {
          return portStatesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public com.futurewei.alioth.controller.schema.Port.PortState getPortStates(int index) {
        if (portStatesBuilder_ == null) {
          return portStates_.get(index);
        } else {
          return portStatesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public Builder setPortStates(
          int index, com.futurewei.alioth.controller.schema.Port.PortState value) {
        if (portStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePortStatesIsMutable();
          portStates_.set(index, value);
          onChanged();
        } else {
          portStatesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public Builder setPortStates(
          int index, com.futurewei.alioth.controller.schema.Port.PortState.Builder builderForValue) {
        if (portStatesBuilder_ == null) {
          ensurePortStatesIsMutable();
          portStates_.set(index, builderForValue.build());
          onChanged();
        } else {
          portStatesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public Builder addPortStates(com.futurewei.alioth.controller.schema.Port.PortState value) {
        if (portStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePortStatesIsMutable();
          portStates_.add(value);
          onChanged();
        } else {
          portStatesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public Builder addPortStates(
          int index, com.futurewei.alioth.controller.schema.Port.PortState value) {
        if (portStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePortStatesIsMutable();
          portStates_.add(index, value);
          onChanged();
        } else {
          portStatesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public Builder addPortStates(
          com.futurewei.alioth.controller.schema.Port.PortState.Builder builderForValue) {
        if (portStatesBuilder_ == null) {
          ensurePortStatesIsMutable();
          portStates_.add(builderForValue.build());
          onChanged();
        } else {
          portStatesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public Builder addPortStates(
          int index, com.futurewei.alioth.controller.schema.Port.PortState.Builder builderForValue) {
        if (portStatesBuilder_ == null) {
          ensurePortStatesIsMutable();
          portStates_.add(index, builderForValue.build());
          onChanged();
        } else {
          portStatesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public Builder addAllPortStates(
          java.lang.Iterable<? extends com.futurewei.alioth.controller.schema.Port.PortState> values) {
        if (portStatesBuilder_ == null) {
          ensurePortStatesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, portStates_);
          onChanged();
        } else {
          portStatesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public Builder clearPortStates() {
        if (portStatesBuilder_ == null) {
          portStates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          portStatesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public Builder removePortStates(int index) {
        if (portStatesBuilder_ == null) {
          ensurePortStatesIsMutable();
          portStates_.remove(index);
          onChanged();
        } else {
          portStatesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public com.futurewei.alioth.controller.schema.Port.PortState.Builder getPortStatesBuilder(
          int index) {
        return getPortStatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public com.futurewei.alioth.controller.schema.Port.PortStateOrBuilder getPortStatesOrBuilder(
          int index) {
        if (portStatesBuilder_ == null) {
          return portStates_.get(index);  } else {
          return portStatesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public java.util.List<? extends com.futurewei.alioth.controller.schema.Port.PortStateOrBuilder> 
           getPortStatesOrBuilderList() {
        if (portStatesBuilder_ != null) {
          return portStatesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(portStates_);
        }
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public com.futurewei.alioth.controller.schema.Port.PortState.Builder addPortStatesBuilder() {
        return getPortStatesFieldBuilder().addBuilder(
            com.futurewei.alioth.controller.schema.Port.PortState.getDefaultInstance());
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public com.futurewei.alioth.controller.schema.Port.PortState.Builder addPortStatesBuilder(
          int index) {
        return getPortStatesFieldBuilder().addBuilder(
            index, com.futurewei.alioth.controller.schema.Port.PortState.getDefaultInstance());
      }
      /**
       * <code>repeated .aliothcontroller.PortState port_states = 3;</code>
       */
      public java.util.List<com.futurewei.alioth.controller.schema.Port.PortState.Builder> 
           getPortStatesBuilderList() {
        return getPortStatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.futurewei.alioth.controller.schema.Port.PortState, com.futurewei.alioth.controller.schema.Port.PortState.Builder, com.futurewei.alioth.controller.schema.Port.PortStateOrBuilder> 
          getPortStatesFieldBuilder() {
        if (portStatesBuilder_ == null) {
          portStatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.futurewei.alioth.controller.schema.Port.PortState, com.futurewei.alioth.controller.schema.Port.PortState.Builder, com.futurewei.alioth.controller.schema.Port.PortStateOrBuilder>(
                  portStates_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          portStates_ = null;
        }
        return portStatesBuilder_;
      }

      private java.util.List<com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState> securityGroupStates_ =
        java.util.Collections.emptyList();
      private void ensureSecurityGroupStatesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          securityGroupStates_ = new java.util.ArrayList<com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState>(securityGroupStates_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState, com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState.Builder, com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupStateOrBuilder> securityGroupStatesBuilder_;

      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public java.util.List<com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState> getSecurityGroupStatesList() {
        if (securityGroupStatesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(securityGroupStates_);
        } else {
          return securityGroupStatesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public int getSecurityGroupStatesCount() {
        if (securityGroupStatesBuilder_ == null) {
          return securityGroupStates_.size();
        } else {
          return securityGroupStatesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState getSecurityGroupStates(int index) {
        if (securityGroupStatesBuilder_ == null) {
          return securityGroupStates_.get(index);
        } else {
          return securityGroupStatesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public Builder setSecurityGroupStates(
          int index, com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState value) {
        if (securityGroupStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSecurityGroupStatesIsMutable();
          securityGroupStates_.set(index, value);
          onChanged();
        } else {
          securityGroupStatesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public Builder setSecurityGroupStates(
          int index, com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState.Builder builderForValue) {
        if (securityGroupStatesBuilder_ == null) {
          ensureSecurityGroupStatesIsMutable();
          securityGroupStates_.set(index, builderForValue.build());
          onChanged();
        } else {
          securityGroupStatesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public Builder addSecurityGroupStates(com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState value) {
        if (securityGroupStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSecurityGroupStatesIsMutable();
          securityGroupStates_.add(value);
          onChanged();
        } else {
          securityGroupStatesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public Builder addSecurityGroupStates(
          int index, com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState value) {
        if (securityGroupStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSecurityGroupStatesIsMutable();
          securityGroupStates_.add(index, value);
          onChanged();
        } else {
          securityGroupStatesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public Builder addSecurityGroupStates(
          com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState.Builder builderForValue) {
        if (securityGroupStatesBuilder_ == null) {
          ensureSecurityGroupStatesIsMutable();
          securityGroupStates_.add(builderForValue.build());
          onChanged();
        } else {
          securityGroupStatesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public Builder addSecurityGroupStates(
          int index, com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState.Builder builderForValue) {
        if (securityGroupStatesBuilder_ == null) {
          ensureSecurityGroupStatesIsMutable();
          securityGroupStates_.add(index, builderForValue.build());
          onChanged();
        } else {
          securityGroupStatesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public Builder addAllSecurityGroupStates(
          java.lang.Iterable<? extends com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState> values) {
        if (securityGroupStatesBuilder_ == null) {
          ensureSecurityGroupStatesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, securityGroupStates_);
          onChanged();
        } else {
          securityGroupStatesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public Builder clearSecurityGroupStates() {
        if (securityGroupStatesBuilder_ == null) {
          securityGroupStates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          securityGroupStatesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public Builder removeSecurityGroupStates(int index) {
        if (securityGroupStatesBuilder_ == null) {
          ensureSecurityGroupStatesIsMutable();
          securityGroupStates_.remove(index);
          onChanged();
        } else {
          securityGroupStatesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState.Builder getSecurityGroupStatesBuilder(
          int index) {
        return getSecurityGroupStatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupStateOrBuilder getSecurityGroupStatesOrBuilder(
          int index) {
        if (securityGroupStatesBuilder_ == null) {
          return securityGroupStates_.get(index);  } else {
          return securityGroupStatesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public java.util.List<? extends com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupStateOrBuilder> 
           getSecurityGroupStatesOrBuilderList() {
        if (securityGroupStatesBuilder_ != null) {
          return securityGroupStatesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(securityGroupStates_);
        }
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState.Builder addSecurityGroupStatesBuilder() {
        return getSecurityGroupStatesFieldBuilder().addBuilder(
            com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState.getDefaultInstance());
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState.Builder addSecurityGroupStatesBuilder(
          int index) {
        return getSecurityGroupStatesFieldBuilder().addBuilder(
            index, com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState.getDefaultInstance());
      }
      /**
       * <code>repeated .aliothcontroller.SecurityGroupState security_group_states = 4;</code>
       */
      public java.util.List<com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState.Builder> 
           getSecurityGroupStatesBuilderList() {
        return getSecurityGroupStatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState, com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState.Builder, com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupStateOrBuilder> 
          getSecurityGroupStatesFieldBuilder() {
        if (securityGroupStatesBuilder_ == null) {
          securityGroupStatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState, com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupState.Builder, com.futurewei.alioth.controller.schema.SecurityGroup.SecurityGroupStateOrBuilder>(
                  securityGroupStates_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          securityGroupStates_ = null;
        }
        return securityGroupStatesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:aliothcontroller.GoalState)
    }

    // @@protoc_insertion_point(class_scope:aliothcontroller.GoalState)
    private static final com.futurewei.alioth.controller.schema.Goalstate.GoalState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.futurewei.alioth.controller.schema.Goalstate.GoalState();
    }

    public static com.futurewei.alioth.controller.schema.Goalstate.GoalState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GoalState>
        PARSER = new com.google.protobuf.AbstractParser<GoalState>() {
      public GoalState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GoalState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GoalState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GoalState> getParserForType() {
      return PARSER;
    }

    public com.futurewei.alioth.controller.schema.Goalstate.GoalState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aliothcontroller_GoalState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aliothcontroller_GoalState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017goalstate.proto\022\020aliothcontroller\032\tvpc" +
      ".proto\032\014subnet.proto\032\nport.proto\032\023securi" +
      "tygroup.proto\"\350\001\n\tGoalState\022.\n\nvpc_state" +
      "s\030\001 \003(\0132\032.aliothcontroller.VpcState\0224\n\rs" +
      "ubnet_states\030\002 \003(\0132\035.aliothcontroller.Su" +
      "bnetState\0220\n\013port_states\030\003 \003(\0132\033.aliothc" +
      "ontroller.PortState\022C\n\025security_group_st" +
      "ates\030\004 \003(\0132$.aliothcontroller.SecurityGr" +
      "oupStateB(\n&com.futurewei.alioth.control" +
      "ler.schemab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.futurewei.alioth.controller.schema.Vpc.getDescriptor(),
          com.futurewei.alioth.controller.schema.Subnet.getDescriptor(),
          com.futurewei.alioth.controller.schema.Port.getDescriptor(),
          com.futurewei.alioth.controller.schema.SecurityGroup.getDescriptor(),
        }, assigner);
    internal_static_aliothcontroller_GoalState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aliothcontroller_GoalState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aliothcontroller_GoalState_descriptor,
        new java.lang.String[] { "VpcStates", "SubnetStates", "PortStates", "SecurityGroupStates", });
    com.futurewei.alioth.controller.schema.Vpc.getDescriptor();
    com.futurewei.alioth.controller.schema.Subnet.getDescriptor();
    com.futurewei.alioth.controller.schema.Port.getDescriptor();
    com.futurewei.alioth.controller.schema.SecurityGroup.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
