= Data-Plane Manager Design Specification
Xiaodong Zhang <xzhang2@futurewei.com>, Liguang Xie <lxie@futurewei.com>
v0.1, 2020-04-30
:toc: right

== Overview

The Data-plane manager is a control plane component responsible of driving network configuration down to the control agents installed on the physical hosts.
It provides a flexible plugin framework which allows different data-plane extension.

=== User Cases

{empty}(1) Port Manger wants to send one new port information to every hosts in the VPC +
(2) Security Group Manager wants to send one new security group to hosts in the VPC

== Service Requirements

=== Basic Requirements

[arabic]
. Provide a flexible plugin framework which allows different data-plane extensions.
. OVS extension supports integration with OVS
. Reliably connecting to hosts through various paths including normal path (kafka) and fast path (gPRC)
. Configurable retry mechanism when connection to hosts is unstable
. Working together with other services including port manager and security group manager.
. Concurrency control mechanism should be provided to process multiple concurrent network configuration programming requests.

=== Advanced Requirements

Fall back mechanism from one path to the other, for example, from fast path to normal path, or from normal path to rescue path

== Data-Plane Microservice Design

=== Architecture

TBD by @haboy52581