apiVersion: v1
kind: Service
metadata:
  name: ignite-master
  labels:
    app: ignite
    role: master
    tier: backend
spec:
  ports:
    - port: 10800
      targetPort: 10800
  selector:
    app: ignite
    role: master
    tier: backend
