apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignite-master
  labels:
    app: ignite
spec:
  selector:
    matchLabels:
      app: ignite
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: ignite
        role: master
        tier: backend
    spec:
      containers:
        - name: master
          image: apacheignite/ignite:2.8.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 10800
