---
apiVersion: v1
kind: Service
metadata:
  name: alcor
  labels:
    app: alcor
spec:
  type: ClusterIP
  selector:
    app: alcor
  ports:
    - protocol: TCP
      port: 8080
      name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: alcor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alcor
    spec:
      containers:
        - name: alcor
          image: fwnetworking/controller
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1