#!/bin/bash
#ping node_manager (port 9007) local IP and MAC are changed to that of ACA's IP and MAC.
# If running on container then log on to ACA container and check its IP and MAC and use them here.
# Node ID: 1112a4d4-ffff-4ece-b3f0-8d36e3d85002
curl -X POST --header "Content-Type: application/json" --header "Accept: */*" -d '{
  "host_info": {
    "local_ip": "10.213.43.161",
    "mac_address": "90:17:ac:c1:30:68",
    "node_id": "1112a4d4-ffff-4ece-b3f0-8d36e3d85001",
    "node_name": "node1",
    "server_port": 8080,
    "veth": "eth0"
  }
}' "http://localhost:9007/nodes"


