#!/bin/bash

# Using route manager (port 9002)
curl -X POST -H "Content-Type: application/json" -H "Accept: */*" -d '{
  "router": {
    "admin_state_up": true,
    "availability_zone_hints": [
      "string"
    ],
    "availability_zones": [
      "string"
    ],
    "conntrack_helpers": [
      "string"
    ],
    "description": "string",
    "distributed": true,
    "external_gateway_info": {
      "enable_snat": true,
      "external_fixed_ips": [
      ],
      "network_id": "9192a4d4-ffff-4ece-b3f0-8d36e3d88001"
    },
    "flavor_id": "string",
    "gateway_ports": [
    ],
    "ha": true,
    "id": "11112801-d675-4688-a63f-dcda8d327f50",
    "name": "router1",
    "owner": "9192a4d4-ffff-4ece-b3f0-8d36e3d88001",
    "project_id": "3dda2801-d675-4688-a63f-dcda8d327f50",
    "revision_number": 0,
    "routetable": {
    },
    "service_type_id": "string",
    "status": "BUILD",
    "tags": [
      "string"
    ],
    "tenant_id": "3dda2801-d675-4688-a63f-dcda8d327f50"
  }
}' "http://localhost:9003/project/3dda2801-d675-4688-a63f-dcda8d327f50/routers"

