package com.futurewei.alcor.dataplane.utils;

import com.futurewei.alcor.schema.*;
import com.futurewei.alcor.web.entity.dataplane.NetworkConfiguration;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class GoalStateUtilTest {
  private static final Logger LOG = LoggerFactory.getLogger(GoalStateUtilTest.class);

  GoalStateUtil goalStateUtil;

  @Before
  public void setup() {
    this.goalStateUtil = new GoalStateUtil();
  }

  @After
  public void destroy() {
    this.goalStateUtil = null;
  }

  @Test
  public void transformNorthToSouthBulkCreatePort() throws InterruptedException {

    String input =
        "{\n"
            + "  \"rsType\": \"PORT\",\n"
            + "  \"opType\": \"CREATE\",\n"
            + "  \"allOrNone\": true,\n"
            + "  \"portStates\": [\n"
            + "    {\n"
            + "      \"bindingHostIP\": \"1.2.3.4\",\n"
            + "      \"subnetEntities\": [\n"
            + "        {\n"
            + "          \"tunnelId\": 88888,\n"
            + "          \"vpcId\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"cidr\": \"192.168.1.0/24\",\n"
            + "          \"availabilityZone\": \"uswest-1\",\n"
            + "          \"gatewayIp\": \"192.168.1.1\",\n"
            + "          \"dhcpEnable\": false,\n"
            + "          \"dnsPublishFixedIp\": false,\n"
            + "          \"useDefaultSubnetpool\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"name\": \"test_subnet1\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"vpcEntities\": [\n"
            + "        {\n"
            + "          \"cidr\": \"192.168.0.0/16\",\n"
            + "          \"adminStateUp\": false,\n"
            + "          \"portSecurityEnabled\": false,\n"
            + "          \"routerExternal\": false,\n"
            + "          \"shared\": false,\n"
            + "          \"vlanTransparent\": false,\n"
            + "          \"isDefault\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"name\": \"test_vpc\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"adminStateUp\": true,\n"
            + "      \"macAddress\": \"86:ea:77:ad:52:55\",\n"
            + "      \"vethName\": \"veth0\",\n"
            + "      \"fastPath\": true,\n"
            + "      \"fixedIps\": [\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"ipAddress\": \"192.168.1.2\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"ipAddress\": \"192.168.1.3\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"bindingHostId\": \"ephost_0\",\n"
            + "      \"networkNamespace\": \"/var/run/netns/test_netw_ns\",\n"
            + "      \"portSecurityEnabled\": false,\n"
            + "      \"revisionNumber\": 0,\n"
            + "      \"resourceRequest\": 0,\n"
            + "      \"uplinkStatusPropagation\": false,\n"
            + "      \"macLearningEnabled\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d3\",\n"
            + "      \"name\": \"test_cni_port2\",\n"
            + "      \"description\": \"\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"bindingHostIP\": \"1.2.3.4\",\n"
            + "      \"subnetEntities\": [\n"
            + "        {\n"
            + "          \"tunnelId\": 88889,\n"
            + "          \"vpcId\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"cidr\": \"192.168.2.0/24\",\n"
            + "          \"availabilityZone\": \"uswest-1\",\n"
            + "          \"gatewayIp\": \"192.168.2.1\",\n"
            + "          \"dhcpEnable\": false,\n"
            + "          \"dnsPublishFixedIp\": false,\n"
            + "          \"useDefaultSubnetpool\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"name\": \"test_subnet2\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"vpcEntities\": [\n"
            + "        {\n"
            + "          \"cidr\": \"192.168.0.0/16\",\n"
            + "          \"adminStateUp\": false,\n"
            + "          \"portSecurityEnabled\": false,\n"
            + "          \"routerExternal\": false,\n"
            + "          \"shared\": false,\n"
            + "          \"vlanTransparent\": false,\n"
            + "          \"isDefault\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"name\": \"test_vpc\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"adminStateUp\": true,\n"
            + "      \"macAddress\": \"86:ea:77:ad:52:56\",\n"
            + "      \"vethName\": \"veth0\",\n"
            + "      \"fastPath\": true,\n"
            + "      \"fixedIps\": [\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"ipAddress\": \"192.168.2.4\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"ipAddress\": \"192.168.2.5\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"bindingHostId\": \"ephost_0\",\n"
            + "      \"networkNamespace\": \"/var/run/netns/test_netw_ns\",\n"
            + "      \"portSecurityEnabled\": false,\n"
            + "      \"revisionNumber\": 0,\n"
            + "      \"resourceRequest\": 0,\n"
            + "      \"uplinkStatusPropagation\": false,\n"
            + "      \"macLearningEnabled\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d0\",\n"
            + "      \"name\": \"test_cni_port3\",\n"
            + "      \"description\": \"\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"bindingHostIP\": \"1.2.3.6\",\n"
            + "      \"subnetEntities\": [\n"
            + "        {\n"
            + "          \"tunnelId\": 88889,\n"
            + "          \"vpcId\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"cidr\": \"192.168.2.0/24\",\n"
            + "          \"availabilityZone\": \"uswest-1\",\n"
            + "          \"gatewayIp\": \"192.168.2.1\",\n"
            + "          \"dhcpEnable\": false,\n"
            + "          \"dnsPublishFixedIp\": false,\n"
            + "          \"useDefaultSubnetpool\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"name\": \"test_subnet2\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"vpcEntities\": [\n"
            + "        {\n"
            + "          \"cidr\": \"192.168.0.0/16\",\n"
            + "          \"adminStateUp\": false,\n"
            + "          \"portSecurityEnabled\": false,\n"
            + "          \"routerExternal\": false,\n"
            + "          \"shared\": false,\n"
            + "          \"vlanTransparent\": false,\n"
            + "          \"isDefault\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"name\": \"test_vpc\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"adminStateUp\": true,\n"
            + "      \"macAddress\": \"86:ea:77:ad:52:57\",\n"
            + "      \"vethName\": \"veth0\",\n"
            + "      \"fastPath\": true,\n"
            + "      \"fixedIps\": [\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"ipAddress\": \"192.168.2.2\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"ipAddress\": \"192.168.2.3\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"bindingHostId\": \"ephost_0\",\n"
            + "      \"networkNamespace\": \"/var/run/netns/test_netw_ns\",\n"
            + "      \"portSecurityEnabled\": false,\n"
            + "      \"revisionNumber\": 0,\n"
            + "      \"resourceRequest\": 0,\n"
            + "      \"uplinkStatusPropagation\": false,\n"
            + "      \"macLearningEnabled\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d6\",\n"
            + "      \"name\": \"test_cni_port4\",\n"
            + "      \"description\": \"\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"bindingHostIP\": \"1.2.3.6\",\n"
            + "      \"subnetEntities\": [\n"
            + "        {\n"
            + "          \"tunnelId\": 88888,\n"
            + "          \"vpcId\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"cidr\": \"192.168.1.0/24\",\n"
            + "          \"availabilityZone\": \"uswest-1\",\n"
            + "          \"gatewayIp\": \"192.168.1.1\",\n"
            + "          \"dhcpEnable\": false,\n"
            + "          \"dnsPublishFixedIp\": false,\n"
            + "          \"useDefaultSubnetpool\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"name\": \"test_subnet1\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"vpcEntities\": [\n"
            + "        {\n"
            + "          \"cidr\": \"192.168.0.0/16\",\n"
            + "          \"adminStateUp\": false,\n"
            + "          \"portSecurityEnabled\": false,\n"
            + "          \"routerExternal\": false,\n"
            + "          \"shared\": false,\n"
            + "          \"vlanTransparent\": false,\n"
            + "          \"isDefault\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"name\": \"test_vpc\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"adminStateUp\": true,\n"
            + "      \"macAddress\": \"86:ea:77:ad:52:58\",\n"
            + "      \"vethName\": \"veth0\",\n"
            + "      \"fastPath\": true,\n"
            + "      \"fixedIps\": [\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"ipAddress\": \"192.168.1.2\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"ipAddress\": \"192.168.1.3\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"bindingHostId\": \"ephost_0\",\n"
            + "      \"networkNamespace\": \"/var/run/netns/test_netw_ns\",\n"
            + "      \"portSecurityEnabled\": false,\n"
            + "      \"revisionNumber\": 0,\n"
            + "      \"resourceRequest\": 0,\n"
            + "      \"uplinkStatusPropagation\": false,\n"
            + "      \"macLearningEnabled\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d7\",\n"
            + "      \"name\": \"test_cni_port5\",\n"
            + "      \"description\": \"\"\n"
            + "    }\n"
            + "  ],\n"
            + "  \"vpcs\": [\n"
            + "    {\n"
            + "      \"cidr\": \"192.168.0.0/16\",\n"
            + "      \"adminStateUp\": false,\n"
            + "      \"portSecurityEnabled\": false,\n"
            + "      \"routerExternal\": false,\n"
            + "      \"shared\": false,\n"
            + "      \"vlanTransparent\": false,\n"
            + "      \"isDefault\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "      \"name\": \"test_vpc\",\n"
            + "      \"description\": \"\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"cidr\": \"192.168.0.0/16\",\n"
            + "      \"adminStateUp\": false,\n"
            + "      \"portSecurityEnabled\": false,\n"
            + "      \"routerExternal\": false,\n"
            + "      \"shared\": false,\n"
            + "      \"vlanTransparent\": false,\n"
            + "      \"isDefault\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "      \"name\": \"test_vpc\",\n"
            + "      \"description\": \"\"\n"
            + "    }\n"
            + "  ],\n"
            + "  \"subnets\": [\n"
            + "    {\n"
            + "      \"tunnelId\": 88888,\n"
            + "      \"vpcId\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "      \"cidr\": \"192.168.1.0/24\",\n"
            + "      \"availabilityZone\": \"uswest-1\",\n"
            + "      \"gatewayIp\": \"192.168.1.1\",\n"
            + "      \"dhcpEnable\": false,\n"
            + "      \"dnsPublishFixedIp\": false,\n"
            + "      \"useDefaultSubnetpool\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "      \"name\": \"test_subnet1\",\n"
            + "      \"description\": \"\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"tunnelId\": 88889,\n"
            + "      \"vpcId\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "      \"cidr\": \"192.168.2.0/24\",\n"
            + "      \"availabilityZone\": \"uswest-1\",\n"
            + "      \"gatewayIp\": \"192.168.2.1\",\n"
            + "      \"dhcpEnable\": false,\n"
            + "      \"dnsPublishFixedIp\": false,\n"
            + "      \"useDefaultSubnetpool\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "      \"name\": \"test_subnet2\",\n"
            + "      \"description\": \"\"\n"
            + "    }\n"
            + "  ],\n"
            + "  \"securityGroupEntities\": [\n"
            + "    {},\n"
            + "    {}\n"
            + "  ]\n"
            + "}";
    String result =
        "{\n"
            + "  \"1.2.3.6\": {\n"
            + "    \"bitField0_\": 0,\n"
            + "    \"formatVersion_\": 0,\n"
            + "    \"vpcStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"id_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"projectId_\": \"\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"192.168.0.0/16\",\n"
            + "          \"tunnelId_\": 0,\n"
            + "          \"subnetIds_\": [],\n"
            + "          \"routes_\": [],\n"
            + "          \"transitRouters_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": 1986295063\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": 1596323463\n"
            + "      },\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"id_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"projectId_\": \"\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"192.168.0.0/16\",\n"
            + "          \"tunnelId_\": 0,\n"
            + "          \"subnetIds_\": [],\n"
            + "          \"routes_\": [],\n"
            + "          \"transitRouters_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": -1872096044\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": 1372131056\n"
            + "      }\n"
            + "    ],\n"
            + "    \"subnetStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 0,\n"
            + "          \"id_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"\",\n"
            + "          \"tunnelId_\": 88888,\n"
            + "          \"dhcpEnable_\": false,\n"
            + "          \"availabilityZone_\": \"\",\n"
            + "          \"primaryDns_\": \"\",\n"
            + "          \"secondaryDns_\": \"\",\n"
            + "          \"transitSwitches_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": -2079552576\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -1209216071\n"
            + "      },\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 0,\n"
            + "          \"id_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"\",\n"
            + "          \"tunnelId_\": 88889,\n"
            + "          \"dhcpEnable_\": false,\n"
            + "          \"availabilityZone_\": \"\",\n"
            + "          \"primaryDns_\": \"\",\n"
            + "          \"secondaryDns_\": \"\",\n"
            + "          \"transitSwitches_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": -1947791283\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -1683105870\n"
            + "      }\n"
            + "    ],\n"
            + "    \"portStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"messageType_\": 1,\n"
            + "          \"id_\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d6\",\n"
            + "          \"networkType_\": 0,\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"\",\n"
            + "          \"name_\": \"test_cni_port4\",\n"
            + "          \"networkNs_\": \"\",\n"
            + "          \"macAddress_\": \"86:ea:77:ad:52:57\",\n"
            + "          \"adminStateUp_\": true,\n"
            + "          \"fixedIps_\": [\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "              \"ipAddress_\": \"192.168.2.2\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1439385702\n"
            + "            },\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "              \"ipAddress_\": \"192.168.2.3\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1439385673\n"
            + "            }\n"
            + "          ],\n"
            + "          \"allowAddressPairs_\": [],\n"
            + "          \"securityGroupIds_\": [],\n"
            + "          \"vethName_\": \"\",\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": -184747492\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -1968022894\n"
            + "      },\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"messageType_\": 1,\n"
            + "          \"id_\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d7\",\n"
            + "          \"networkType_\": 0,\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"\",\n"
            + "          \"name_\": \"test_cni_port5\",\n"
            + "          \"networkNs_\": \"\",\n"
            + "          \"macAddress_\": \"86:ea:77:ad:52:58\",\n"
            + "          \"adminStateUp_\": true,\n"
            + "          \"fixedIps_\": [\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "              \"ipAddress_\": \"192.168.1.2\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1439470440\n"
            + "            },\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "              \"ipAddress_\": \"192.168.1.3\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1439470411\n"
            + "            }\n"
            + "          ],\n"
            + "          \"allowAddressPairs_\": [],\n"
            + "          \"securityGroupIds_\": [],\n"
            + "          \"vethName_\": \"\",\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": 1410201339\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": 1335820245\n"
            + "      }\n"
            + "    ],\n"
            + "    \"securityGroupStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 0,\n"
            + "          \"revisionNumber_\": 0,\n"
            + "          \"id_\": \"\",\n"
            + "          \"projectId_\": \"\",\n"
            + "          \"vpcId_\": \"\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"securityGroupRules_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": 0\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": 0\n"
            + "      }\n"
            + "    ],\n"
            + "    \"dhcpStates_\": [],\n"
            + "    \"memoizedIsInitialized\": 1,\n"
            + "    \"unknownFields\": {\n"
            + "      \"fields\": {},\n"
            + "      \"fieldsDescending\": {}\n"
            + "    },\n"
            + "    \"memoizedSize\": -1,\n"
            + "    \"memoizedHashCode\": 0\n"
            + "  },\n"
            + "  \"1.2.3.4\": {\n"
            + "    \"bitField0_\": 0,\n"
            + "    \"formatVersion_\": 0,\n"
            + "    \"vpcStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"id_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"projectId_\": \"\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"192.168.0.0/16\",\n"
            + "          \"tunnelId_\": 0,\n"
            + "          \"subnetIds_\": [],\n"
            + "          \"routes_\": [],\n"
            + "          \"transitRouters_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": 1986295063\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": 1596323463\n"
            + "      },\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"id_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"projectId_\": \"\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"192.168.0.0/16\",\n"
            + "          \"tunnelId_\": 0,\n"
            + "          \"subnetIds_\": [],\n"
            + "          \"routes_\": [],\n"
            + "          \"transitRouters_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": -1872096044\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": 1372131056\n"
            + "      }\n"
            + "    ],\n"
            + "    \"subnetStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 0,\n"
            + "          \"id_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"\",\n"
            + "          \"tunnelId_\": 88888,\n"
            + "          \"dhcpEnable_\": false,\n"
            + "          \"availabilityZone_\": \"\",\n"
            + "          \"primaryDns_\": \"\",\n"
            + "          \"secondaryDns_\": \"\",\n"
            + "          \"transitSwitches_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": -2079552576\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -1209216071\n"
            + "      },\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 0,\n"
            + "          \"id_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"\",\n"
            + "          \"tunnelId_\": 88889,\n"
            + "          \"dhcpEnable_\": false,\n"
            + "          \"availabilityZone_\": \"\",\n"
            + "          \"primaryDns_\": \"\",\n"
            + "          \"secondaryDns_\": \"\",\n"
            + "          \"transitSwitches_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": -1947791283\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -1683105870\n"
            + "      }\n"
            + "    ],\n"
            + "    \"portStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"messageType_\": 1,\n"
            + "          \"id_\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d0\",\n"
            + "          \"networkType_\": 0,\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"\",\n"
            + "          \"name_\": \"test_cni_port3\",\n"
            + "          \"networkNs_\": \"\",\n"
            + "          \"macAddress_\": \"86:ea:77:ad:52:56\",\n"
            + "          \"adminStateUp_\": true,\n"
            + "          \"fixedIps_\": [\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "              \"ipAddress_\": \"192.168.2.4\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1439385644\n"
            + "            },\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "              \"ipAddress_\": \"192.168.2.5\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1439385615\n"
            + "            }\n"
            + "          ],\n"
            + "          \"allowAddressPairs_\": [],\n"
            + "          \"securityGroupIds_\": [],\n"
            + "          \"vethName_\": \"\",\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": -1802215612\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -1629958118\n"
            + "      },\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"messageType_\": 1,\n"
            + "          \"id_\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d3\",\n"
            + "          \"networkType_\": 0,\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"\",\n"
            + "          \"name_\": \"test_cni_port2\",\n"
            + "          \"networkNs_\": \"\",\n"
            + "          \"macAddress_\": \"86:ea:77:ad:52:55\",\n"
            + "          \"adminStateUp_\": true,\n"
            + "          \"fixedIps_\": [\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "              \"ipAddress_\": \"192.168.1.2\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1439470440\n"
            + "            },\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "              \"ipAddress_\": \"192.168.1.3\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1439470411\n"
            + "            }\n"
            + "          ],\n"
            + "          \"allowAddressPairs_\": [],\n"
            + "          \"securityGroupIds_\": [],\n"
            + "          \"vethName_\": \"\",\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": 2048119097\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -1639401253\n"
            + "      }\n"
            + "    ],\n"
            + "    \"securityGroupStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 0,\n"
            + "          \"revisionNumber_\": 0,\n"
            + "          \"id_\": \"\",\n"
            + "          \"projectId_\": \"\",\n"
            + "          \"vpcId_\": \"\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"securityGroupRules_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": 0\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": 0\n"
            + "      }\n"
            + "    ],\n"
            + "    \"dhcpStates_\": [],\n"
            + "    \"memoizedIsInitialized\": 1,\n"
            + "    \"unknownFields\": {\n"
            + "      \"fields\": {},\n"
            + "      \"fieldsDescending\": {}\n"
            + "    },\n"
            + "    \"memoizedSize\": -1,\n"
            + "    \"memoizedHashCode\": 0\n"
            + "  }\n"
            + "}";
    handleData(input, result);
  }

  private void handleData(String input, String result) {
    Gson g = new Gson();
    NetworkConfiguration networkConfiguration = g.fromJson(input, NetworkConfiguration.class);
    final Map<String, Goalstate.GoalState> programOutput =
        goalStateUtil.transformNorthToSouth(networkConfiguration);

    final Map<String, Goalstate.GoalState> expectedOutput =
        (Map<String, Goalstate.GoalState>)
            g.fromJson(result, new TypeToken<Map<String, Goalstate.GoalState>>() {}.getType());
    programOutput.entrySet().stream()
        .forEach(
            e -> {
              Assert.assertTrue(
                  compareInternalEntity(e.getValue(), expectedOutput.get(e.getKey())));
            });
  }

  private boolean compareInternalEntity(Goalstate.GoalState o1, Goalstate.GoalState o2) {
    List<Port.PortState> portStatesList = new ArrayList(o1.getPortStatesList());
    List<Subnet.SubnetState> subnetStatesList = new ArrayList((o1.getSubnetStatesList()));
    List<Vpc.VpcState> vpcStatesList = new ArrayList(o1.getVpcStatesList());
    List<SecurityGroup.SecurityGroupState> securityGroupStatesList =
        o1.getSecurityGroupStatesList();

    List<Port.PortState> portStatesList1 = new ArrayList(o2.getPortStatesList());
    List<Subnet.SubnetState> subnetStatesList1 = new ArrayList(o2.getSubnetStatesList());
    List<Vpc.VpcState> vpcStatesList1 = new ArrayList(o2.getVpcStatesList());
    List<SecurityGroup.SecurityGroupState> securityGroupStatesList1 =
        o2.getSecurityGroupStatesList();

    portStatesList.removeAll(portStatesList1);
    subnetStatesList.removeAll(subnetStatesList1);
    vpcStatesList1.removeAll(vpcStatesList);
    boolean b = portStatesList.isEmpty() && subnetStatesList.isEmpty() && vpcStatesList1.isEmpty();
    LOG.debug(String.valueOf(b));
    return b;
  }

  @Test
  public void transformNorthToSouthNeighborInfo() {
    String input =
        "{\n"
            + "  \"rsType\": \"PORT\",\n"
            + "  \"opType\": \"CREATE\",\n"
            + "  \"allOrNone\": true,\n"
            + "  \"portStates\": [\n"
            + "    {\n"
            + "      \"neighborIps\": [\n"
            + "        {\n"
            + "          \"hostIp\": \"1.2.3.6\",\n"
            + "          \"hostId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"portId\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d7\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"bindingHostIP\": \"1.2.3.4\",\n"
            + "      \"subnetEntities\": [\n"
            + "        {\n"
            + "          \"tunnelId\": 88888,\n"
            + "          \"vpcId\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"cidr\": \"192.168.1.0/24\",\n"
            + "          \"availabilityZone\": \"uswest-1\",\n"
            + "          \"gatewayIp\": \"192.168.1.1\",\n"
            + "          \"dhcpEnable\": false,\n"
            + "          \"dnsPublishFixedIp\": false,\n"
            + "          \"useDefaultSubnetpool\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"name\": \"test_subnet1\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"vpcEntities\": [\n"
            + "        {\n"
            + "          \"cidr\": \"192.168.0.0/16\",\n"
            + "          \"adminStateUp\": false,\n"
            + "          \"portSecurityEnabled\": false,\n"
            + "          \"routerExternal\": false,\n"
            + "          \"shared\": false,\n"
            + "          \"vlanTransparent\": false,\n"
            + "          \"isDefault\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"name\": \"test_vpc\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"adminStateUp\": true,\n"
            + "      \"macAddress\": \"86:ea:77:ad:52:55\",\n"
            + "      \"vethName\": \"veth0\",\n"
            + "      \"fastPath\": true,\n"
            + "      \"fixedIps\": [\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"ipAddress\": \"192.168.1.2\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"ipAddress\": \"192.168.1.3\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"bindingHostId\": \"ephost_0\",\n"
            + "      \"networkNamespace\": \"/var/run/netns/test_netw_ns\",\n"
            + "      \"portSecurityEnabled\": false,\n"
            + "      \"revisionNumber\": 0,\n"
            + "      \"resourceRequest\": 0,\n"
            + "      \"uplinkStatusPropagation\": false,\n"
            + "      \"macLearningEnabled\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d3\",\n"
            + "      \"name\": \"test_cni_port2\",\n"
            + "      \"description\": \"\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"neighborIps\": [\n"
            + "        {\n"
            + "          \"hostIp\": \"1.2.3.6\",\n"
            + "          \"hostId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"portId\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d6\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"bindingHostIP\": \"1.2.3.4\",\n"
            + "      \"subnetEntities\": [\n"
            + "        {\n"
            + "          \"tunnelId\": 88889,\n"
            + "          \"vpcId\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"cidr\": \"192.168.2.0/24\",\n"
            + "          \"availabilityZone\": \"uswest-1\",\n"
            + "          \"gatewayIp\": \"192.168.2.1\",\n"
            + "          \"dhcpEnable\": false,\n"
            + "          \"dnsPublishFixedIp\": false,\n"
            + "          \"useDefaultSubnetpool\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"name\": \"test_subnet2\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"vpcEntities\": [\n"
            + "        {\n"
            + "          \"cidr\": \"192.168.0.0/16\",\n"
            + "          \"adminStateUp\": false,\n"
            + "          \"portSecurityEnabled\": false,\n"
            + "          \"routerExternal\": false,\n"
            + "          \"shared\": false,\n"
            + "          \"vlanTransparent\": false,\n"
            + "          \"isDefault\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"name\": \"test_vpc\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"adminStateUp\": true,\n"
            + "      \"macAddress\": \"86:ea:77:ad:52:56\",\n"
            + "      \"vethName\": \"veth0\",\n"
            + "      \"fastPath\": true,\n"
            + "      \"fixedIps\": [\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"ipAddress\": \"192.168.2.4\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"ipAddress\": \"192.168.2.5\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"bindingHostId\": \"ephost_0\",\n"
            + "      \"networkNamespace\": \"/var/run/netns/test_netw_ns\",\n"
            + "      \"portSecurityEnabled\": false,\n"
            + "      \"revisionNumber\": 0,\n"
            + "      \"resourceRequest\": 0,\n"
            + "      \"uplinkStatusPropagation\": false,\n"
            + "      \"macLearningEnabled\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d0\",\n"
            + "      \"name\": \"test_cni_port3\",\n"
            + "      \"description\": \"\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"neighborIps\": [\n"
            + "        {\n"
            + "          \"hostIp\": \"1.2.3.4\",\n"
            + "          \"hostId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"portId\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d0\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"bindingHostIP\": \"1.2.3.6\",\n"
            + "      \"subnetEntities\": [\n"
            + "        {\n"
            + "          \"tunnelId\": 88889,\n"
            + "          \"vpcId\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"cidr\": \"192.168.2.0/24\",\n"
            + "          \"availabilityZone\": \"uswest-1\",\n"
            + "          \"gatewayIp\": \"192.168.2.1\",\n"
            + "          \"dhcpEnable\": false,\n"
            + "          \"dnsPublishFixedIp\": false,\n"
            + "          \"useDefaultSubnetpool\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"name\": \"test_subnet2\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"vpcEntities\": [\n"
            + "        {\n"
            + "          \"cidr\": \"192.168.0.0/16\",\n"
            + "          \"adminStateUp\": false,\n"
            + "          \"portSecurityEnabled\": false,\n"
            + "          \"routerExternal\": false,\n"
            + "          \"shared\": false,\n"
            + "          \"vlanTransparent\": false,\n"
            + "          \"isDefault\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"name\": \"test_vpc\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"adminStateUp\": true,\n"
            + "      \"macAddress\": \"86:ea:77:ad:52:57\",\n"
            + "      \"vethName\": \"veth0\",\n"
            + "      \"fastPath\": true,\n"
            + "      \"fixedIps\": [\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"ipAddress\": \"192.168.2.2\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"ipAddress\": \"192.168.2.3\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"bindingHostId\": \"ephost_0\",\n"
            + "      \"networkNamespace\": \"/var/run/netns/test_netw_ns\",\n"
            + "      \"portSecurityEnabled\": false,\n"
            + "      \"revisionNumber\": 0,\n"
            + "      \"resourceRequest\": 0,\n"
            + "      \"uplinkStatusPropagation\": false,\n"
            + "      \"macLearningEnabled\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d6\",\n"
            + "      \"name\": \"test_cni_port4\",\n"
            + "      \"description\": \"\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"neighborIps\": [\n"
            + "        {\n"
            + "          \"hostIp\": \"1.2.3.4\",\n"
            + "          \"hostId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"portId\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d3\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"bindingHostIP\": \"1.2.3.6\",\n"
            + "      \"subnetEntities\": [\n"
            + "        {\n"
            + "          \"tunnelId\": 88888,\n"
            + "          \"vpcId\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"cidr\": \"192.168.1.0/24\",\n"
            + "          \"availabilityZone\": \"uswest-1\",\n"
            + "          \"gatewayIp\": \"192.168.1.1\",\n"
            + "          \"dhcpEnable\": false,\n"
            + "          \"dnsPublishFixedIp\": false,\n"
            + "          \"useDefaultSubnetpool\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"name\": \"test_subnet1\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"vpcEntities\": [\n"
            + "        {\n"
            + "          \"cidr\": \"192.168.0.0/16\",\n"
            + "          \"adminStateUp\": false,\n"
            + "          \"portSecurityEnabled\": false,\n"
            + "          \"routerExternal\": false,\n"
            + "          \"shared\": false,\n"
            + "          \"vlanTransparent\": false,\n"
            + "          \"isDefault\": false,\n"
            + "          \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"id\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"name\": \"test_vpc\",\n"
            + "          \"description\": \"\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"adminStateUp\": true,\n"
            + "      \"macAddress\": \"86:ea:77:ad:52:58\",\n"
            + "      \"vethName\": \"veth0\",\n"
            + "      \"fastPath\": true,\n"
            + "      \"fixedIps\": [\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"ipAddress\": \"192.168.1.2\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"subnetId\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"ipAddress\": \"192.168.1.3\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"bindingHostId\": \"ephost_0\",\n"
            + "      \"networkNamespace\": \"/var/run/netns/test_netw_ns\",\n"
            + "      \"portSecurityEnabled\": false,\n"
            + "      \"revisionNumber\": 0,\n"
            + "      \"resourceRequest\": 0,\n"
            + "      \"uplinkStatusPropagation\": false,\n"
            + "      \"macLearningEnabled\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d7\",\n"
            + "      \"name\": \"test_cni_port5\",\n"
            + "      \"description\": \"\"\n"
            + "    }\n"
            + "  ],\n"
            + "  \"vpcs\": [\n"
            + "    {\n"
            + "      \"cidr\": \"192.168.0.0/16\",\n"
            + "      \"adminStateUp\": false,\n"
            + "      \"portSecurityEnabled\": false,\n"
            + "      \"routerExternal\": false,\n"
            + "      \"shared\": false,\n"
            + "      \"vlanTransparent\": false,\n"
            + "      \"isDefault\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "      \"name\": \"test_vpc\",\n"
            + "      \"description\": \"\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"cidr\": \"192.168.0.0/16\",\n"
            + "      \"adminStateUp\": false,\n"
            + "      \"portSecurityEnabled\": false,\n"
            + "      \"routerExternal\": false,\n"
            + "      \"shared\": false,\n"
            + "      \"vlanTransparent\": false,\n"
            + "      \"isDefault\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "      \"name\": \"test_vpc\",\n"
            + "      \"description\": \"\"\n"
            + "    }\n"
            + "  ],\n"
            + "  \"subnets\": [\n"
            + "    {\n"
            + "      \"tunnelId\": 88888,\n"
            + "      \"vpcId\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "      \"cidr\": \"192.168.1.0/24\",\n"
            + "      \"availabilityZone\": \"uswest-1\",\n"
            + "      \"gatewayIp\": \"192.168.1.1\",\n"
            + "      \"dhcpEnable\": false,\n"
            + "      \"dnsPublishFixedIp\": false,\n"
            + "      \"useDefaultSubnetpool\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "      \"name\": \"test_subnet1\",\n"
            + "      \"description\": \"\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"tunnelId\": 88889,\n"
            + "      \"vpcId\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "      \"cidr\": \"192.168.2.0/24\",\n"
            + "      \"availabilityZone\": \"uswest-1\",\n"
            + "      \"gatewayIp\": \"192.168.2.1\",\n"
            + "      \"dhcpEnable\": false,\n"
            + "      \"dnsPublishFixedIp\": false,\n"
            + "      \"useDefaultSubnetpool\": false,\n"
            + "      \"projectId\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "      \"id\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "      \"name\": \"test_subnet2\",\n"
            + "      \"description\": \"\"\n"
            + "    }\n"
            + "  ],\n"
            + "  \"securityGroupEntities\": [\n"
            + "    {},\n"
            + "    {}\n"
            + "  ]\n"
            + "}";
    String result =
        "{\n"
            + "  \"1.2.3.6\": {\n"
            + "    \"bitField0_\": 0,\n"
            + "    \"formatVersion_\": 0,\n"
            + "    \"vpcStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"id_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"projectId_\": \"\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"192.168.0.0/16\",\n"
            + "          \"tunnelId_\": 0,\n"
            + "          \"subnetIds_\": [],\n"
            + "          \"routes_\": [],\n"
            + "          \"transitRouters_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": 2008624373\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -872301739\n"
            + "      },\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"id_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"projectId_\": \"\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"192.168.0.0/16\",\n"
            + "          \"tunnelId_\": 0,\n"
            + "          \"subnetIds_\": [],\n"
            + "          \"routes_\": [],\n"
            + "          \"transitRouters_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": -1849766734\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -1096494146\n"
            + "      }\n"
            + "    ],\n"
            + "    \"subnetStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 0,\n"
            + "          \"id_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"\",\n"
            + "          \"tunnelId_\": 88888,\n"
            + "          \"dhcpEnable_\": false,\n"
            + "          \"availabilityZone_\": \"\",\n"
            + "          \"primaryDns_\": \"\",\n"
            + "          \"secondaryDns_\": \"\",\n"
            + "          \"transitSwitches_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": -939142530\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -2044645358\n"
            + "      },\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 0,\n"
            + "          \"id_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"\",\n"
            + "          \"tunnelId_\": 88889,\n"
            + "          \"dhcpEnable_\": false,\n"
            + "          \"availabilityZone_\": \"\",\n"
            + "          \"primaryDns_\": \"\",\n"
            + "          \"secondaryDns_\": \"\",\n"
            + "          \"transitSwitches_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": -807381237\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": 1776432139\n"
            + "      }\n"
            + "    ],\n"
            + "    \"portStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"messageType_\": 0,\n"
            + "          \"id_\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d3\",\n"
            + "          \"networkType_\": 5,\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"\",\n"
            + "          \"name_\": \"test_cni_port5\",\n"
            + "          \"networkNs_\": \"\",\n"
            + "          \"macAddress_\": \"86:ea:77:ad:52:58\",\n"
            + "          \"adminStateUp_\": true,\n"
            + "          \"hostInfo_\": {\n"
            + "            \"ipAddress_\": \"1.2.3.4\",\n"
            + "            \"macAddress_\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d3\",\n"
            + "            \"memoizedIsInitialized\": 1,\n"
            + "            \"unknownFields\": {\n"
            + "              \"fields\": {},\n"
            + "              \"fieldsDescending\": {}\n"
            + "            },\n"
            + "            \"memoizedSize\": -1,\n"
            + "            \"memoizedHashCode\": -2030109568\n"
            + "          },\n"
            + "          \"fixedIps_\": [\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "              \"ipAddress_\": \"192.168.1.2\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1986480296\n"
            + "            },\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "              \"ipAddress_\": \"192.168.1.3\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1986480267\n"
            + "            }\n"
            + "          ],\n"
            + "          \"allowAddressPairs_\": [],\n"
            + "          \"securityGroupIds_\": [],\n"
            + "          \"vethName_\": \"\",\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": 1338851716\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -2077756844\n"
            + "      },\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"messageType_\": 0,\n"
            + "          \"id_\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d0\",\n"
            + "          \"networkType_\": 5,\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"\",\n"
            + "          \"name_\": \"test_cni_port4\",\n"
            + "          \"networkNs_\": \"\",\n"
            + "          \"macAddress_\": \"86:ea:77:ad:52:57\",\n"
            + "          \"adminStateUp_\": true,\n"
            + "          \"hostInfo_\": {\n"
            + "            \"ipAddress_\": \"1.2.3.4\",\n"
            + "            \"macAddress_\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d0\",\n"
            + "            \"memoizedIsInitialized\": 1,\n"
            + "            \"unknownFields\": {\n"
            + "              \"fields\": {},\n"
            + "              \"fieldsDescending\": {}\n"
            + "            },\n"
            + "            \"memoizedSize\": -1,\n"
            + "            \"memoizedHashCode\": -2030109655\n"
            + "          },\n"
            + "          \"fixedIps_\": [\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "              \"ipAddress_\": \"192.168.2.2\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1986395558\n"
            + "            },\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "              \"ipAddress_\": \"192.168.2.3\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1986395529\n"
            + "            }\n"
            + "          ],\n"
            + "          \"allowAddressPairs_\": [],\n"
            + "          \"securityGroupIds_\": [],\n"
            + "          \"vethName_\": \"\",\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": 826995176\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": 258272680\n"
            + "      }\n"
            + "    ],\n"
            + "    \"securityGroupStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 0,\n"
            + "          \"revisionNumber_\": 0,\n"
            + "          \"id_\": \"\",\n"
            + "          \"projectId_\": \"\",\n"
            + "          \"vpcId_\": \"\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"securityGroupRules_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": 0\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": 0\n"
            + "      }\n"
            + "    ],\n"
            + "    \"dhcpStates_\": [],\n"
            + "    \"memoizedIsInitialized\": 1,\n"
            + "    \"unknownFields\": {\n"
            + "      \"fields\": {},\n"
            + "      \"fieldsDescending\": {}\n"
            + "    },\n"
            + "    \"memoizedSize\": -1,\n"
            + "    \"memoizedHashCode\": 0\n"
            + "  },\n"
            + "  \"1.2.3.4\": {\n"
            + "    \"bitField0_\": 0,\n"
            + "    \"formatVersion_\": 0,\n"
            + "    \"vpcStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"id_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"projectId_\": \"\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"192.168.0.0/16\",\n"
            + "          \"tunnelId_\": 0,\n"
            + "          \"subnetIds_\": [],\n"
            + "          \"routes_\": [],\n"
            + "          \"transitRouters_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": 2008624373\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -872301739\n"
            + "      },\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"id_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"projectId_\": \"\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"192.168.0.0/16\",\n"
            + "          \"tunnelId_\": 0,\n"
            + "          \"subnetIds_\": [],\n"
            + "          \"routes_\": [],\n"
            + "          \"transitRouters_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": -1849766734\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -1096494146\n"
            + "      }\n"
            + "    ],\n"
            + "    \"subnetStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 0,\n"
            + "          \"id_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88039\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"\",\n"
            + "          \"tunnelId_\": 88888,\n"
            + "          \"dhcpEnable_\": false,\n"
            + "          \"availabilityZone_\": \"\",\n"
            + "          \"primaryDns_\": \"\",\n"
            + "          \"secondaryDns_\": \"\",\n"
            + "          \"transitSwitches_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": -939142530\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -2044645358\n"
            + "      },\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 0,\n"
            + "          \"id_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"9192a4d4-ffff-4ece-b3f0-8d36e3d88038\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"cidr_\": \"\",\n"
            + "          \"tunnelId_\": 88889,\n"
            + "          \"dhcpEnable_\": false,\n"
            + "          \"availabilityZone_\": \"\",\n"
            + "          \"primaryDns_\": \"\",\n"
            + "          \"secondaryDns_\": \"\",\n"
            + "          \"transitSwitches_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": -807381237\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": 1776432139\n"
            + "      }\n"
            + "    ],\n"
            + "    \"portStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"messageType_\": 0,\n"
            + "          \"id_\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d7\",\n"
            + "          \"networkType_\": 5,\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"\",\n"
            + "          \"name_\": \"test_cni_port2\",\n"
            + "          \"networkNs_\": \"\",\n"
            + "          \"macAddress_\": \"86:ea:77:ad:52:55\",\n"
            + "          \"adminStateUp_\": true,\n"
            + "          \"hostInfo_\": {\n"
            + "            \"ipAddress_\": \"1.2.3.6\",\n"
            + "            \"macAddress_\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d7\",\n"
            + "            \"memoizedIsInitialized\": 1,\n"
            + "            \"unknownFields\": {\n"
            + "              \"fields\": {},\n"
            + "              \"fieldsDescending\": {}\n"
            + "            },\n"
            + "            \"memoizedSize\": -1,\n"
            + "            \"memoizedHashCode\": -2029995714\n"
            + "          },\n"
            + "          \"fixedIps_\": [\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "              \"ipAddress_\": \"192.168.1.2\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1986480296\n"
            + "            },\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594e\",\n"
            + "              \"ipAddress_\": \"192.168.1.3\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1986480267\n"
            + "            }\n"
            + "          ],\n"
            + "          \"allowAddressPairs_\": [],\n"
            + "          \"securityGroupIds_\": [],\n"
            + "          \"vethName_\": \"\",\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": 1340757696\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -2022483424\n"
            + "      },\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 1,\n"
            + "          \"revisionNumber_\": 1,\n"
            + "          \"messageType_\": 0,\n"
            + "          \"id_\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d6\",\n"
            + "          \"networkType_\": 5,\n"
            + "          \"projectId_\": \"3dda2801-d675-4688-a63f-dcda8d327f50\",\n"
            + "          \"vpcId_\": \"\",\n"
            + "          \"name_\": \"test_cni_port3\",\n"
            + "          \"networkNs_\": \"\",\n"
            + "          \"macAddress_\": \"86:ea:77:ad:52:56\",\n"
            + "          \"adminStateUp_\": true,\n"
            + "          \"hostInfo_\": {\n"
            + "            \"ipAddress_\": \"1.2.3.6\",\n"
            + "            \"macAddress_\": \"f37810eb-7f83-45fa-a4d4-1b31e75399d6\",\n"
            + "            \"memoizedIsInitialized\": 1,\n"
            + "            \"unknownFields\": {\n"
            + "              \"fields\": {},\n"
            + "              \"fieldsDescending\": {}\n"
            + "            },\n"
            + "            \"memoizedSize\": -1,\n"
            + "            \"memoizedHashCode\": -2029995743\n"
            + "          },\n"
            + "          \"fixedIps_\": [\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "              \"ipAddress_\": \"192.168.2.4\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1986395500\n"
            + "            },\n"
            + "            {\n"
            + "              \"subnetId_\": \"a87e0f87-a2d9-44ef-9194-9a62f178594f\",\n"
            + "              \"ipAddress_\": \"192.168.2.5\",\n"
            + "              \"memoizedIsInitialized\": 1,\n"
            + "              \"unknownFields\": {\n"
            + "                \"fields\": {},\n"
            + "                \"fieldsDescending\": {}\n"
            + "              },\n"
            + "              \"memoizedSize\": -1,\n"
            + "              \"memoizedHashCode\": -1986395471\n"
            + "            }\n"
            + "          ],\n"
            + "          \"allowAddressPairs_\": [],\n"
            + "          \"securityGroupIds_\": [],\n"
            + "          \"vethName_\": \"\",\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": 38632708\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": -1129402412\n"
            + "      }\n"
            + "    ],\n"
            + "    \"securityGroupStates_\": [\n"
            + "      {\n"
            + "        \"operationType_\": 0,\n"
            + "        \"configuration_\": {\n"
            + "          \"bitField0_\": 0,\n"
            + "          \"formatVersion_\": 0,\n"
            + "          \"revisionNumber_\": 0,\n"
            + "          \"id_\": \"\",\n"
            + "          \"projectId_\": \"\",\n"
            + "          \"vpcId_\": \"\",\n"
            + "          \"name_\": \"\",\n"
            + "          \"securityGroupRules_\": [],\n"
            + "          \"memoizedIsInitialized\": 1,\n"
            + "          \"unknownFields\": {\n"
            + "            \"fields\": {},\n"
            + "            \"fieldsDescending\": {}\n"
            + "          },\n"
            + "          \"memoizedSize\": -1,\n"
            + "          \"memoizedHashCode\": 0\n"
            + "        },\n"
            + "        \"memoizedIsInitialized\": 1,\n"
            + "        \"unknownFields\": {\n"
            + "          \"fields\": {},\n"
            + "          \"fieldsDescending\": {}\n"
            + "        },\n"
            + "        \"memoizedSize\": -1,\n"
            + "        \"memoizedHashCode\": 0\n"
            + "      }\n"
            + "    ],\n"
            + "    \"dhcpStates_\": [],\n"
            + "    \"memoizedIsInitialized\": 1,\n"
            + "    \"unknownFields\": {\n"
            + "      \"fields\": {},\n"
            + "      \"fieldsDescending\": {}\n"
            + "    },\n"
            + "    \"memoizedSize\": -1,\n"
            + "    \"memoizedHashCode\": 0\n"
            + "  }\n"
            + "}";
    handleData(input,result);
  }
  }
