= Dataplane Abstraction
Eric Li <sze.li@futurewei.com>
v0.1, 2020-03-01
:toc: right

== Introduction

TBD

== Assumptions

. Performance, both control plane programming throughput and latency, is a requirement and priority
. *** UPDATED*** A VPC project network may support more than one type of dataplane (e.g. VXLAN_OVS and VLAN_OVS)

== Current ACA Layered Design

The current ACA implementation already have the core GS parsing logic in one place regardless of the dataplane, until the actual processing of the VPC/Subnet/port configuration which is dataplane dependent, thanks to the implementation of parallel programming workitem design. We can simply put the dataplane dependent code into different class, or do stuff like load library/plugin during runtime.

== Basic flow applicable to all options

. Customer creates a VM from UI or API
. Customer picks an existing VPC and Subnet, or create one on the creation wizard (UI)
. The VM creation API call goes to Nova scheduler pick an appropriate compute host to place the VM
. Nova compute will call Alcor Controller (was Neutron server) to allocate network
.. ***UPDATED*** see if we can have Nova compute to pass down the host info to Alcor Controller
. Nova host agent will add tap device to connect the VM to OVS br_int
. Alcor controller push down goal state to the corresponding compute host(s) and network node(s)
. Two major endpoint host goal state updates to point out:
.. Port operation: CREATE: to setup the network device and start dataplane programming
.. Port operation: FINALIZE: complete rest of dataplane programming and mark the device as ready to use
.. Investigate to see if we can combine the two port operations

== Abstraction at Alcor Control Plane ***UPDATED***

. ACA and Alcor Controller will be configured with supported network type and default during startup time (e.g. config file)
.. Note that this approach does support concurrent network type (e.g. VXLAN and VLAN) on the host 
. When Nova compute calls Alcor Controller to allocate network, it can either
.. NOT specify the dataplane type, so it will use the Alcor Controller default
.. Specify the network type, Alcor controller will leverage that for processing, ACA running on compute host will try to see if it is supported, else return UNSUPPORTED_DATAPLANE
.. ***QUESTION*** Do we want to go with always explicit approach?
. Alcor Controller can specify which network type to program or just use default when sending down Port operation: CREATE
.. Note that Neutron server is always explicit on the network type when sending down port detail
. When ACA receives goal state update with Port operation: CREATE (in one shot, not calling operation FINALIZE anymore)
.. It will setup the network device according to the specified network type or use default type if not specified
.. Alcor Controller is responsible to aggregate all the port/router update status to provide the final "port state up" status

*src/schema/proto3/goalstate.proto*
[source,java]
------------------------------------------------------------
enum NetworkType { // ***NEW*** ***UPDATED***
    VXLAN = 0;      // use the default type configured in compute host ACA
    VLAN = 1;
    GRE = 2;
    GENEVE = 3;
}

/* snipped out */

message GoalState {
    NetworkType network_type = 1; // ***NEW***
    repeated VpcState vpc_states = 2;
    repeated SubnetState subnet_states = 3;
    repeated PortState port_states = 4;
    repeated SecurityGroupState security_group_states = 5;
}
------------------------------------------------------------

*src/schema/proto3/goalstateprovisioner.proto*
[source,java]
------------------------------------------------------------
enum OperationStatus {
    SUCCESS = 0;
    FAILURE = 1;
    INVALID_ARG = 2;
    UNSUPPORTED_NETWORK_TYPE = 3 // ***NEW***
}

/* snipped out */

message GoalStateOperationReply {

    repeated GoalStateOperationStatus operation_statuses = 1;
    uint32 message_total_operation_time = 2;

    message GoalStateOperationStatus {
        string resource_id = 1;
        ResourceType resource_type = 2;
        OperationType operation_type = 3;
        OperationStatus operation_status = 4;
        uint32 dataplane_programming_time = 5;
        uint32 network_configuration_time = 6;
        uint32 state_elapse_time = 7;
    }
}
------------------------------------------------------------
