# MIT License
# Copyright(c) 2022 Futurewei Cloud
#     Permission is hereby granted,
#     free of charge, to any person obtaining a copy of this software and associated documentation files(the "Software"), to deal in the Software without restriction,
#     including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and / or sell copies of the Software, and to permit persons
#     to whom the Software is furnished to do so, subject to the following conditions:
#     The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
#     WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# DB
- db/ignite/ignite_alcor_dpm.yaml
- db/ignite/ignite_alcor_ip.yaml
- db/ignite/ignite_alcor_mac.yaml
- db/ignite/ignite_alcor_ncm.yaml
- db/ignite/ignite_alcor_port.yaml
- db/ignite/ignite_alcor.yaml

# Services
- services/api-gateway.yaml
- services/dpm_manager.yaml
- services/elastic_ip_manager.yaml
- services/gateway_manager.yaml
- services/mac_manager.yaml
- services/network_config_manager.yaml
- services/node_manager.yaml
- services/port_manager.yaml
- services/private_ip_manager.yaml
- services/quota_manager.yaml
- services/route_manager.yaml
- services/sg_manager.yaml
- services/subnet_manager.yaml
- services/vpc_manager.yaml
