apiVersion: v1
kind: Service
metadata:
  name: ignite-alcor-service
  labels:
    app: ignite-alcor
spec:
  ports:
    - name: start
      port: 8080
      targetPort: 8080
    - name: sql
      port: 10800
      targetPort: 10800
  selector:
    app: ignite-alcor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ignite-alcor
  name: ignite-alcor
spec:
  selector:
    matchLabels:
      app: ignite-alcor
  replicas: 3
  template:
    metadata:
      labels:
        app: ignite-alcor
    spec:
      containers:
        - name: ignite-alcor-node
          image: apacheignite/ignite
          imagePullPolicy: IfNotPresent
#          env:
#            - name: OPTION_LIBS
#              value: ignite-kubernetes
#            - name: CONFIG_URI
#              value: /opt/ignite/config/ignite-config.xml
          ports:
            - name: port8080
              containerPort: 8080
            - name: port11211
              containerPort: 11211 # REST port number.
            - name: port47100
              containerPort: 47100 # communication SPI port number.
            - name: port47500
              containerPort: 47500 # discovery SPI port number.
            - name: port49112
              containerPort: 49112 # JMX port number.
            - name: port10800
              containerPort: 10800 # SQL port number.
            - name: port10900
              containerPort: 10900 # Thin clients port number.
          volumeMounts:
            - name: ignite-alcor-config-volume
              mountPath: /opt/ignite/config
      volumes:
        - name: ignite-alcor-config-volume