apiVersion: v1
kind: Service
metadata:
  name: redis-route-sr
  labels:
    name: redis-route
spec:
  ports:
    - port: 6380
      targetPort: 6379
  selector:
    app: redis-route
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-route
  name: redis-route
spec:
  selector:
    matchLabels:
      app: redis-route
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-route
    spec:
      containers:
        - image: redis
        #- image: fwnetworking/controller:redis
          name: redis-route
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379