apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: vpcmanager-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vpcmanager
  # if minReplicas is less than Deployment replicas value, it may cause scale down
  minReplicas: 5
  maxReplicas: 10
  metrics:
#   Set the average usage rate of the cpu, scale up if it exceeds 50
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageUtilization
          averageUtilization: 50
#    The average data volume per second reaches 1000 for scaling up
#    - type: Pods
#      pods:
#        metric:
#          name: packets-per-second
#        target:
#          type: AverageValue
#          averageValue: 1k

#    The value is derived from Ingress "main-route", scale up when the number of requests per second in Ingress reaches 2000
#    - type: Object
#      object:
#        metric:
#          name: requests-per-second
#        describedObject:
#          apiVersion: networking.k8s.io/v1beta1
#          kind: Ingress
#          name: main-route
#        target:
#          kind: Value
#          value: 10k

# HPA's current status data
status:
  observedGeneration: 1
  lastScaleTime: <some-time>
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
    - type: Resource
      resource:
        name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
#    - type: Object
#      object:
#        metric:
#          name: requests-per-second
#        describedObject:
#          apiVersion: networking.k8s.io/v1beta1
#          kind: Ingress
#          name: main-route
#        current:
#          value: 10k
