#!/bin/bash
# Using Port manager, create the end port:

curl -X PUT --header "Content-Type: application/json" --header "Accept: */*" -d '{
  "port": {
    "device_id": "4628f3df-48ef-4d0c-9b55-167ff1f67178",
"device_owner": "compute:nova",
"binding:host_id": "node2",
    "fast_path": true
}
}' "http://localhost:9006/project/3dda2801-d675-4688-a63f-dcda8d327f50/ports/40b7c9b6-f997-40c9-9e83-d21d94457176"

