#!/bin/bash
# Using Port manager, create the end port:

curl -X PUT --header "Content-Type: application/json" --header "Accept: */*" -d '{
  "port": {
    "device_id": "4628f3df-48ef-4d0c-9b55-167ff1f67177",
"device_owner": "compute:nova",
"binding:host_id": "node1",
    "fast_path": true
}
}' "http://localhost:9006/project/3dda2801-d675-4688-a63f-dcda8d327f50/ports/374f5359-6b94-4a50-a810-12cc70bd4438"

