#!/bin/bash
# Using Port manager, create the end port:

curl -X POST --header "Content-Type: application/json" --header "Accept: */*" -d '{
  "port": {
    "device_id": "4628f3df-48ef-4d0c-9b55-167ff1f67177",
    "admin_state_up": true,
    "network_id": "9192a4d4-ffff-4ece-b3f0-8d36e3d88001",
    "security_groups": [
      "3dda2801-d675-4688-a63f-dcda8d111111"
    ],
    "tenant_id": "3dda2801-d675-4688-a63f-dcda8d327f50"
  }
}' "http://localhost:9006/project/3dda2801-d675-4688-a63f-dcda8d327f50/ports"

