= Alcor Rbac Design
v0.1, 2020-08-14
:toc: right
:imagesdir: ../../images

== Introduction
Alcor Rbac (Role based access control) is designed to be compatible with neutron Rbac. Both are based on Openstack Keystone
 roles while Alcor Rbac is at a finer granularity level at microservices compared to Neutron at the whole service level.
Alcor microservices load rbac rules at from its own rbac_policy.json file under the resource directory of each microservice.

== Microservices with support of Rbac
Alcor some common services (VPC, Subnet, Port, Security-group, Eip, eg) support resources should support Rbac. In this services
there are some resources operations access should control by roles.

== Authorization implementation
A request come API GW service first, API GW will verify the token in http request. And API GW will add a new http header
'X-Token-info'. Microservice will get the token info from http header. +
Not all microservices apis require Rbac. We only need to add the @Rbac annotation to the APIs that need to support Rbac,
And set the 'resource' attribute of the @Rbac annotation. Finally, you need to introduce RbacConfiguration to the microservice entry class. +
Like this.
......
@EnableAsync
@SpringBootApplication
@Import({DbBaseConfiguration.class, JsonHandlerConfiguration.class, RbacConfiguration.class})
public class SubnetApplication {

    public static void main(String[] args) {
        SpringApplication.run(SubnetApplication.class, args);
    }

}
......
We only need to set these modifiers for the microservices.
THe RbacManager automatically completes the rest of the work.

== Access Type
Alcor rbac supports a few of access type

. admin_only -- Only admin role can access
. rule_any -- Every one can access
. admin_or_owner -- Admin role or resource owner can access
. multi_roles -- Only specified roles can access
. multi_roles_or_owner -- Only specified roles or admin can access

== Permission Granularity
Alcor can support method and resource field check granularity.

. Method -- The method granularity determines whether the user role can access the method.
. Resource field -- The field granularity determines whether a user role can be accessed, modified, deleted, or added

== WorkFlow
Rbac check around a http request.

. a request come
. rbac check method access, failed throw exception
. rbac check field access, failed throw exception
. handle request
. rbac check field access, failed hide the field
. response the request

== rbac_policy.json example
....
{
  "serviceRules": [
    {
      "name": "create_vpc",
      "method_type": "POST",
      "description": "create a vpc",
      "rule_type": "rule_any",
      "roles": [],
      "field_rbac_rules": [
        {
          "name": "shared",
          "description": "create a shared vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        },
        {
          "name": "router:external",
          "description": "create an external vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        },
        {
          "name": "is_default",
          "description": "Specify ''is_default'' attribute when creating a vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        },
        {
          "name": "port_security_enabled",
          "description": "Specify ''port_security_enabled'' attribute when creating a vpc",
          "rule_type": "rule_any",
          "roles": []
        },
        {
          "name": "segments",
          "description": "Specify ''segments'' attribute when creating a vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        },
        {
          "name": "provider:network_type",
          "description": "Specify ''provider:network_type'' attribute when creating a vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        },
        {
          "name": "provider:physical_network",
          "description": "Specify ''provider:physical_network'' attribute when creating a vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        },
        {
          "name": "provider:segmentation_id",
          "description": "Specify ''provider:segmentation_id'' attribute when creating a vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        }
      ]
    },
    {
      "name": "get_vpc",
      "method_type": "GET",
      "description": "Get or list vpc",
      "rule_type": "admin_or_owner",
      "roles": ["admin"],
      "field_rbac_rules": [
        {
          "name": "router:external",
          "description": "Get ''router:external'' attribute of a vpc",
          "rule_type": "rule_any",
          "roles": []
        },
        {
          "name": "segments",
          "description": "Get ''segments'' attribute of a vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        },
        {
          "name": "provider:network_type",
          "description": "Get ''provider:network_type'' attribute of a vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        },
        {
          "name": "provider:physical_network",
          "description": "Get ''provider:physical_network'' attribute of a vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        },
        {
          "name": "provider:segmentation_id",
          "description": "Get ''provider:segmentation_id'' attribute of a vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        }
      ]
    },
    {
      "name": "update_vpc",
      "method_type": "PUT",
      "description": "Update a vpc",
      "rule_type": "admin_or_owner",
      "roles": ["admin"],
      "field_rbac_rules": [
        {
          "name": "shared",
          "description": "Update ''shared'' attribute of a vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        },
        {
          "name": "is_default",
          "description": "Update ''is_default'' attribute of a vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        },
        {
          "name": "router:external",
          "description": "Update ''router:external'' attribute of a vpc",
          "rule_type": "rule_any",
          "roles": []
        },
        {
          "name": "segments",
          "description": "Update ''segments'' attribute of a vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        },
        {
          "name": "provider:network_type",
          "description": "Update ''provider:network_type'' attribute of a vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        },
        {
          "name": "provider:physical_network",
          "description": "Update ''provider:physical_network'' attribute of a vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        },
        {
          "name": "provider:segmentation_id",
          "description": "Update ''provider:segmentation_id'' attribute of a vpc",
          "rule_type": "admin_only",
          "roles": ["admin"]
        },
        {
          "name": "port_security_enabled",
          "description": "Update ''port_security_enabled'' attribute of a vpc",
          "rule_type": "admin_or_owner",
          "roles": ["admin"]
        }
      ]
    },
    {
      "name": "delete_vpc",
      "method_type": "DELETE",
      "description": "Delete a vpc",
      "rule_type": "admin_or_owner",
      "roles": ["admin"]
    }
  ]
}
....