= Key System Flows
Eric Li <sze.li@futurewei.com>, Liguang Xie <lxie@futurewei.com>, Chun-Jen (James) Chung<cchung@futurewei.com>
v0.1, 2020-09-18
:toc: right
:imagesdir: ../../images

NOTE: This document is under development

== Architecture Overview

TBD: add picture


== Requirements

We want to have a design that is:

. fast provision - end to end port provision including security group < 100ms
. agile update - allow granular update/add/delete one or more security group rule on host (as oppose to push down all the rules for an update) 
. scalable - needs to handle 100,000 ports in a VPC, and 1,000,000 machines in a region
. high performance - low latency VM to VM communication with port security enabled
. lean - minimal resource overhead on host (e.g. namespace?, bridges, linux device, linux kernel)
. fast migration - VMs migration should have network blackout time < a few seconds

Note that Security groups are stateful - meaning allowed ingress traffic are allowed to flow out, and vice versa. Therefore, a connection tracking mechanism is required for its implementation. 


== Neutron Security Group

=== Challanges BEFORE April 2016 OpenStack Mitaka release

1. Adds a linux bridge between each VM port and OVS bridge (br-int)
2. Uses linux devices and linux kernel to support IP Tables implementation
3. Update of security group rule requires the whole security group to be pushed down to compute host to recompile the IP Tables chain (TBD: review Neutron Agent behavior)
4. This IP Tables implementation cannot be offloaded to hardware, except using a SoC/ARM based NIC which has capability to run the whole linux OS

TBD: add picture


=== AFTER April 2016 OpenStack Mitaka release

The OpenStack community recognized the challange of IP Tables implementation for security group rules. With OVS implementation of connection tracking <<ovs-conntrack>>, many open source solutions including ovs_dpdk_firewall<<intel>> and dragonflow<<dragonflow-security-group>> start leveraging it for OpenStack. It is natural for OpenStack neutron to adopt it. OpenStack Mitaka introduced offical OVS Firewall driver, which addressed many of the issues in the prior releases. But Alcor can do even better than that.


== Design approach

The Security Group design uses OVS and OpenFlow, building on the latest Neutron OVS firewall rule approach. It offers the following advantages compare to Neutron:   

. Direct connection from VM port to OVS, don't need extra linux bridge/linux devices/linux kernel/IP Tables
. Direct and not chatty Alcor controller to Alcor control agent communication
. Support Delta update: Update of security group rule only require the changed rule to be push down to compute host
. Only one set of security group rule is configured in OVS to be shared with all ports using it
. Enable scale and performance from ground up, addressing the biggest pain point on neutron
. OpenFlow rules can be offloaded to hardware

Our highlighted improvement is to use only one OpenFlow rule per security group rule, to be shared with all the assoicated ports on the compute host. That will promote the scale and performance compare to Neutron. To support this, we will use openflow "packet register" storage and a global or local host unique ID to mark the ports assoicated for a particular security group, to use the corresponding security group rule. Remote security group rule will use similar approach explained below.

Note: Each packet register is 64 bits wide (OVS has 8 of them) and maskable <<ovs-fields>>. To support a port which assoicated with multiple SGs, we will set one bit which maps to a SG. Therefore, we may have a limit of 512 SGs on a compute host for the ports to share. We can fall back to non-sharing SG when the limit reached (similar to neutron's non-sharing SG OVS implementation).


=== Remote Security Group Rule handling

A Security Group rule can reference to a remote security group for both ingress and egress traffic. When a security group rule is added to security group A, customer can set security group B as the source (for ingress rule) or destination (for egress rule). This allows ports associated with security group B to access ports that are port of security group A, and vice versa.

The default security group has rules that allows ports assoicated with it to talk to each other.

To support this using the minimal set of OpenFlow rules, we will need to mark remote ports with its assoicated security group. We will update our neighbor configuration schema to include assoicated security group IDs. For L3 neighbor, we will leverage on-demand rule so that the OpenFlow rule for the marking is only setup when needed (for egress). For L2 neighbor, we will go ahead to setup its OpenFlow rule for the marking since it is limited by the subnet size. We will consider doing on-demand rule for L2 neighbors in the future if needed.


== Default Security Group

ALLOW: Direction=Egress, Ether Type=IPv4, IP Protocol=Any, Port Range=Any, Remote IP Prefix=0.0.0.0/0
ALLOW: Direction=Egress, Ether Type=IPv6, IP Protocol=Any, Port Range=Any, Remote IP Prefix=::/0
ALLOW: Direction=Ingress, Ether Type=IPv4, IP Protocol=Any, Port Range=Any, Remote SG=default
ALLOW: Direction=Ingress, Ether Type=IPv6, IP Protocol=Any, Port Range=Any, Remote SG=default

User can add or delete rules but cannot remove this security group.


== Customer created Security Group

ALLOW: Direction=Egress, Ether Type=IPv4, IP Protocol=Any, Port Range=Any, Remote IP Prefix=0.0.0.0/0
ALLOW: Direction=Egress, Ether Type=IPv6, IP Protocol=Any, Port Range=Any, Remote IP Prefix=::/0

User can add or delete rules or remove this security group.


== Hidden Security Group Policies

With port security enabled, since all the traffic are blocked by default. A list of hidden security group rule are allowed to enable basic connectivity, which include allowing for ICMP, ICMP6, ARP, DHCP, DHCPv6, SSH and connection tracking. The system will also enabled a rule to only allow traffic coming out from the port has the assigned virtual mac address to disallow mac spoofing. See later session for a sample set of openflow rules when a VM port has been added.


== Workflow on Security Group programming

TBD: add workflow


== Sample Openflow rule for Security Group

Below is the full set of OpenFlow rules on br-int when a VM is added in a microstack setup:

[source,shell]
------------------------------------------------------------
root@fw0009097:~# microstack.ovs-ofctl dump-flows br-int
 cookie=0x18b5fbabf7b6e3f3, duration=22961.497s, table=0, n_packets=0, n_bytes=0, priority=65535,vlan_tci=0x0fff/0x1fff actions=drop
 cookie=0x18b5fbabf7b6e3f3, duration=22961.231s, table=0, n_packets=39, n_bytes=3432, priority=2,in_port="int-br-ex" actions=drop
 cookie=0x18b5fbabf7b6e3f3, duration=22961.499s, table=0, n_packets=185, n_bytes=18157, priority=0 actions=resubmit(,60)
 cookie=0x18b5fbabf7b6e3f3, duration=22961.499s, table=23, n_packets=0, n_bytes=0, priority=0 actions=drop
 cookie=0x18b5fbabf7b6e3f3, duration=22961.497s, table=24, n_packets=0, n_bytes=0, priority=0 actions=drop
 cookie=0x18b5fbabf7b6e3f3, duration=1156.933s, table=60, n_packets=114, n_bytes=10202, priority=100,in_port="tap0308ac0c-28" actions=load:0x3->NXM_NX_REG5[],load:0x1->NXM_NX_REG6[],resubmit(,71)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.933s, table=60, n_packets=70, n_bytes=7913, priority=90,dl_vlan=1,dl_dst=fa:16:3e:38:c6:87 actions=load:0x3->NXM_NX_REG5[],load:0x1->NXM_NX_REG6[],strip_vlan,resubmit(,81)
 cookie=0x18b5fbabf7b6e3f3, duration=22961.499s, table=60, n_packets=1, n_bytes=42, priority=3 actions=NORMAL
 cookie=0x18b5fbabf7b6e3f3, duration=22960.796s, table=71, n_packets=0, n_bytes=0, priority=110,ct_state=+trk actions=ct_clear,resubmit(,71)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=71, n_packets=0, n_bytes=0, priority=95,icmp6,reg5=0x3,in_port="tap0308ac0c-28",icmp_type=130 actions=resubmit(,94)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=71, n_packets=3, n_bytes=210, priority=95,icmp6,reg5=0x3,in_port="tap0308ac0c-28",icmp_type=133 actions=resubmit(,94)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=71, n_packets=1, n_bytes=78, priority=95,icmp6,reg5=0x3,in_port="tap0308ac0c-28",icmp_type=135 actions=resubmit(,94)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=71, n_packets=0, n_bytes=0, priority=95,icmp6,reg5=0x3,in_port="tap0308ac0c-28",icmp_type=136 actions=resubmit(,94)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=71, n_packets=0, n_bytes=0, priority=70,icmp6,reg5=0x3,in_port="tap0308ac0c-28",icmp_type=134 actions=resubmit(,93)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=71, n_packets=3, n_bytes=126, priority=95,arp,reg5=0x3,in_port="tap0308ac0c-28",dl_src=fa:16:3e:38:c6:87,arp_spa=192.168.222.248 actions=resubmit(,94)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=71, n_packets=101, n_bytes=8742, priority=65,ip,reg5=0x3,in_port="tap0308ac0c-28",dl_src=fa:16:3e:38:c6:87,nw_src=192.168.222.248 actions=ct(table=72,zone=NXM_NX_REG6[0..15])
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=71, n_packets=2, n_bytes=686, priority=80,udp,reg5=0x3,in_port="tap0308ac0c-28",tp_src=68,tp_dst=67 actions=resubmit(,73)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=71, n_packets=0, n_bytes=0, priority=80,udp6,reg5=0x3,in_port="tap0308ac0c-28",tp_src=546,tp_dst=547 actions=resubmit(,73)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=71, n_packets=0, n_bytes=0, priority=70,udp,reg5=0x3,in_port="tap0308ac0c-28",tp_src=67,tp_dst=68 actions=resubmit(,93)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=71, n_packets=0, n_bytes=0, priority=70,udp6,reg5=0x3,in_port="tap0308ac0c-28",tp_src=547,tp_dst=546 actions=resubmit(,93)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=71, n_packets=2, n_bytes=180, priority=65,ipv6,reg5=0x3,in_port="tap0308ac0c-28",dl_src=fa:16:3e:38:c6:87,ipv6_src=fe80::f816:3eff:fe38:c687 actions=ct(table=72,zone=NXM_NX_REG6[0..15])
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=71, n_packets=2, n_bytes=180, priority=10,reg5=0x3,in_port="tap0308ac0c-28" actions=ct_clear,resubmit(,93)
 cookie=0x18b5fbabf7b6e3f3, duration=22960.848s, table=71, n_packets=0, n_bytes=0, priority=0 actions=drop
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=72, n_packets=0, n_bytes=0, priority=74,ct_state=+est-rel-rpl,ipv6,reg5=0x3 actions=resubmit(,73)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=72, n_packets=80, n_bytes=7120, priority=74,ct_state=+est-rel-rpl,ip,reg5=0x3 actions=resubmit(,73)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=72, n_packets=0, n_bytes=0, priority=74,ct_state=+new-est,ipv6,reg5=0x3 actions=resubmit(,73)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=72, n_packets=21, n_bytes=1622, priority=74,ct_state=+new-est,ip,reg5=0x3 actions=resubmit(,73)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=72, n_packets=2, n_bytes=180, priority=50,ct_state=+inv+trk actions=resubmit(,93)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=72, n_packets=0, n_bytes=0, priority=50,ct_mark=0x1,reg5=0x3 actions=resubmit(,93)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=72, n_packets=0, n_bytes=0, priority=50,ct_state=+est-rel+rpl,ct_zone=1,ct_mark=0,reg5=0x3 actions=resubmit(,94)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=72, n_packets=0, n_bytes=0, priority=50,ct_state=-new-est+rel-inv,ct_zone=1,ct_mark=0,reg5=0x3 actions=resubmit(,94)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=72, n_packets=0, n_bytes=0, priority=40,ct_state=-est,reg5=0x3 actions=resubmit(,93)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=72, n_packets=0, n_bytes=0, priority=40,ct_state=+est,ip,reg5=0x3 actions=ct(commit,zone=NXM_NX_REG6[0..15],exec(load:0x1->NXM_NX_CT_MARK[]))
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=72, n_packets=0, n_bytes=0, priority=40,ct_state=+est,ipv6,reg5=0x3 actions=ct(commit,zone=NXM_NX_REG6[0..15],exec(load:0x1->NXM_NX_CT_MARK[]))
 cookie=0x18b5fbabf7b6e3f3, duration=22960.837s, table=72, n_packets=0, n_bytes=0, priority=0 actions=drop
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=73, n_packets=0, n_bytes=0, priority=100,reg6=0x1,dl_dst=fa:16:3e:38:c6:87 actions=load:0x3->NXM_NX_REG5[],resubmit(,81)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=73, n_packets=21, n_bytes=1622, priority=90,ct_state=+new-est,ip,reg5=0x3 actions=ct(commit,zone=NXM_NX_REG6[0..15]),resubmit(,91)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=73, n_packets=0, n_bytes=0, priority=90,ct_state=+new-est,ipv6,reg5=0x3 actions=ct(commit,zone=NXM_NX_REG6[0..15]),resubmit(,91)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=73, n_packets=82, n_bytes=7806, priority=80,reg5=0x3 actions=resubmit(,94)
 cookie=0x18b5fbabf7b6e3f3, duration=22960.828s, table=73, n_packets=0, n_bytes=0, priority=0 actions=drop
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=81, n_packets=3, n_bytes=126, priority=100,arp,reg5=0x3 actions=output:"tap0308ac0c-28"
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=81, n_packets=0, n_bytes=0, priority=100,icmp6,reg5=0x3,icmp_type=130 actions=output:"tap0308ac0c-28"
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=81, n_packets=0, n_bytes=0, priority=100,icmp6,reg5=0x3,icmp_type=135 actions=output:"tap0308ac0c-28"
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=81, n_packets=0, n_bytes=0, priority=100,icmp6,reg5=0x3,icmp_type=136 actions=output:"tap0308ac0c-28"
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=81, n_packets=2, n_bytes=762, priority=95,udp,reg5=0x3,tp_src=67,tp_dst=68 actions=output:"tap0308ac0c-28"
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=81, n_packets=0, n_bytes=0, priority=95,udp6,reg5=0x3,tp_src=547,tp_dst=546 actions=output:"tap0308ac0c-28"
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=81, n_packets=65, n_bytes=7025, priority=90,ct_state=-trk,ip,reg5=0x3 actions=ct(table=82,zone=NXM_NX_REG6[0..15])
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=81, n_packets=0, n_bytes=0, priority=90,ct_state=-trk,ipv6,reg5=0x3 actions=ct(table=82,zone=NXM_NX_REG6[0..15])
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=81, n_packets=0, n_bytes=0, priority=80,ct_state=+trk,reg5=0x3 actions=resubmit(,82)
 cookie=0x18b5fbabf7b6e3f3, duration=22960.818s, table=81, n_packets=0, n_bytes=0, priority=0 actions=drop
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=77,ct_state=+est-rel-rpl,tcp,reg5=0x3,tp_dst=22 actions=output:"tap0308ac0c-28"
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=77,ct_state=+new-est,tcp,reg5=0x3,tp_dst=22 actions=ct(commit,zone=NXM_NX_REG6[0..15]),output:"tap0308ac0c-28",resubmit(,92)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=75,ct_state=+est-rel-rpl,icmp,reg5=0x3 actions=output:"tap0308ac0c-28"
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=75,ct_state=+new-est,icmp,reg5=0x3 actions=ct(commit,zone=NXM_NX_REG6[0..15]),output:"tap0308ac0c-28",resubmit(,92)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=70,ct_state=+est-rel-rpl,ip,reg5=0x3 actions=conjunction(8,2/2)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=70,ct_state=+est-rel-rpl,ipv6,reg5=0x3 actions=conjunction(16,2/2)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=70,ct_state=+new-est,ip,reg5=0x3 actions=conjunction(9,2/2)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=70,ct_state=+new-est,ipv6,reg5=0x3 actions=conjunction(17,2/2)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=70,conj_id=8,ct_state=+est-rel-rpl,ip,reg5=0x3 actions=load:0x8->NXM_NX_REG7[],output:"tap0308ac0c-28"
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=70,conj_id=16,ct_state=+est-rel-rpl,ipv6,reg5=0x3 actions=load:0x10->NXM_NX_REG7[],output:"tap0308ac0c-28"
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=70,conj_id=9,ct_state=+new-est,ip,reg5=0x3 actions=load:0x9->NXM_NX_REG7[],ct(commit,zone=NXM_NX_REG6[0..15]),output:"tap0308ac0c-28",resubmit(,92)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=70,conj_id=17,ct_state=+new-est,ipv6,reg5=0x3 actions=load:0x11->NXM_NX_REG7[],ct(commit,zone=NXM_NX_REG6[0..15]),output:"tap0308ac0c-28",resubmit(,92)
 cookie=0x18b5fbabf7b6e3f3, duration=1158.885s, table=82, n_packets=0, n_bytes=0, priority=70,ct_state=+est-rel-rpl,ip,reg6=0x1,nw_src=192.168.222.248 actions=conjunction(8,1/2)
 cookie=0x18b5fbabf7b6e3f3, duration=1158.885s, table=82, n_packets=0, n_bytes=0, priority=70,ct_state=+new-est,ip,reg6=0x1,nw_src=192.168.222.248 actions=conjunction(9,1/2)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=50,ct_state=+inv+trk actions=resubmit(,93)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=50,ct_mark=0x1,reg5=0x3 actions=resubmit(,93)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=65, n_bytes=7025, priority=50,ct_state=+est-rel+rpl,ct_zone=1,ct_mark=0,reg5=0x3 actions=output:"tap0308ac0c-28"
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=50,ct_state=-new-est+rel-inv,ct_zone=1,ct_mark=0,reg5=0x3 actions=output:"tap0308ac0c-28"
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=40,ct_state=-est,reg5=0x3 actions=resubmit(,93)
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=40,ct_state=+est,ip,reg5=0x3 actions=ct(commit,zone=NXM_NX_REG6[0..15],exec(load:0x1->NXM_NX_CT_MARK[]))
 cookie=0x18b5fbabf7b6e3f3, duration=1156.934s, table=82, n_packets=0, n_bytes=0, priority=40,ct_state=+est,ipv6,reg5=0x3 actions=ct(commit,zone=NXM_NX_REG6[0..15],exec(load:0x1->NXM_NX_CT_MARK[]))
 cookie=0x18b5fbabf7b6e3f3, duration=22960.808s, table=82, n_packets=0, n_bytes=0, priority=0 actions=drop
 cookie=0x18b5fbabf7b6e3f3, duration=22960.776s, table=91, n_packets=21, n_bytes=1622, priority=1 actions=resubmit(,94)
 cookie=0x18b5fbabf7b6e3f3, duration=22960.766s, table=92, n_packets=0, n_bytes=0, priority=0 actions=drop
 cookie=0x18b5fbabf7b6e3f3, duration=22960.756s, table=93, n_packets=4, n_bytes=360, priority=0 actions=drop
 cookie=0x18b5fbabf7b6e3f3, duration=22960.785s, table=94, n_packets=110, n_bytes=9842, priority=1 actions=NORMAL
------------------------------------------------------------


== Pending Items

. What happen if host crashed, do we ask the Alcor controller for the whole set of configuration upon restart?


[bibliography]
== References

- [[[ovs-conntrack,1]]] https://ovs-istokes.readthedocs.io/en/latest/tutorials/ovs-conntrack.html
- [[[intel,2]]] https://software.intel.com/content/www/us/en/develop/articles/implementing-an-openstack-security-group-firewall-driver-using-ovs-learn-actions.html
- [[[dragonflow-security-group,3]]] https://galsagie.github.io/2015/12/28/dragonflow-security-groups/
- [[[ovs-fields,4]]] https://www.man7.org/linux/man-pages/man7/ovs-fields.7.html
- [[[ovs-openflow,5]]] https://object-storage-ca-ymq-1.vexxhost.net/swift/v1/6e4619c416ff4bd19e1c087f27a43eea/www-assets-prod/presentation-media/Austin-Summit-SG-firewall-Presentation-v2.3.pdf
- [[[openstack-implementation,6]]]  https://github.com/openstack/neutron/commit/ef29f7eb9a2a37133eacdb7f019b48ec3f9a42c3 
- [[[neutron-security-group,7]]] https://docs.openstack.org/nova/train/admin/security-groups.html
