@startuml
'https://plantuml.com/sequence-diagram

== MQ-> GRPC ==
autonumber

DPM <-> VPCM: VPC info query
DPM ->NM: Query whether target node subscript vpc topic or not
NM ->DPM: Yes
DPM -> targetNode: Node unsubscript API
targetNode -> MQ: Unsubscrpt the topic
targetNode -> DPM: Unsubscript result
DPM -> targetNode: Send goal state with GRPC

== GRPC-> MQ ==
autonumber

DPM <-> VPCM: VPC info query
DPM ->NM: Query whether target node subscript vpc topic or not
NM ->DPM: NO
DPM -> targetNode: Node subscript API(MQ cluster & topicName)
targetNode -> MQ: Subscrpt the topic
targetNode -> DPM: subscript result
DPM -> targetNode: Send goal state with MQ

== keep GRPC ==
autonumber

DPM <-> VPCM: VPC info query
DPM ->NM: Query whether target node subscript vpc topic or not
NM ->DPM: NO
DPM -> targetNode: Send goal state with GRPC

== keep MQ ==
autonumber

DPM <-> VPCM: VPC info query
DPM ->NM: Query whether target node subscript vpc topic or not
NM ->DPM: Yes
DPM -> targetNode: Send goal state with MQ


@enduml