' Copyright 2019 The Alcor Authors.

' Licensed under the Apache License, Version 2.0 (the "License");
'        you may not use this file except in compliance with the License.
'        You may obtain a copy of the License at

'        http://www.apache.org/licenses/LICENSE-2.0

'        Unless required by applicable law or agreed to in writing, software
'        distributed under the License is distributed on an "AS IS" BASIS,
'        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
'        See the License for the specific language governing permissions and
'        limitations under the License.

@startuml

title Workflow of Subnet

skinparam monochrome true
collections "API Gateway" as api
collections "VPC Manager" as VPC
collections "Subnet Manager" as subnet
collections "Port Manager" as port
collections "Route_Manager" as route
collections "Private IP Manager" as ip
collections "Mac Manager" as mac
collections "Security Group Manager" as sg
collections "Data Plane Manager" as dp
collections "Node Manager" as nm
collections Hosts as host

@enduml
