' Copyright 2019 The Alcor Authors.

' Licensed under the Apache License, Version 2.0 (the "License");
'        you may not use this file except in compliance with the License.
'        You may obtain a copy of the License at

'        http://www.apache.org/licenses/LICENSE-2.0

'        Unless required by applicable law or agreed to in writing, software
'        distributed under the License is distributed on an "AS IS" BASIS,
'        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
'        See the License for the specific language governing permissions and
'        limitations under the License.

@startuml

skinparam monochrome true
autonumber "<b>[00]"
actor User as user
participant "Horizon Dashboard/CLI" as frontend
participant Keystone as keystone
participant "Nova-API Server" as novaapi
database "Nova DB" as novadb
participant "Message queue" as queue
participant "Nova-Scheduler" as scheduler
participant "Nova-Compute" as compute
participant "Nova-Conductor" as conductor
participant "Hypervisor" as hypervisor
participant "Glance" as glance
participant "Neutron/Alcor" as network
participant "Cinder" as cinder

note over keystone: REST APIs
/ note over novaapi: REST APIs
/ note over glance: REST APIs
/ note over network: REST APIs
/ note over cinder: REST APIs

user -> frontend: Log in with credential
frontend -> keystone: Send user's credential\nfor authentication
keystone --> frontend: Authenticate the credential\nsend back auth-token
user -> frontend: Launch VM instance\n(nova boot command)
frontend -> novaapi: Convert frontend request to REST API request
novaapi -> keystone: Validation of auth-token\nand access permission
keystone --> novaapi: Send updated authentication\nheaders with roles and permission
novaapi -> novadb: Check for conflicts and\ncreate initial db entry
novadb --> novaapi: DB access response

group Scheduling Nodes
novaapi -> queue: Ask to specify host id for the instance
queue -> scheduler: Schedule picks the request
scheduler -> novadb: Locate a host using filtering and weighing
novadb --> scheduler: Return updated instance entry w/ host id
scheduler -> queue: Send Rpc.cast request to\nnova-compute on the selected\nhost for launching an instance
queue -> compute: Nova-compute picks the request from the queue
end

group Fetching Instance Information
compute -> queue: send the rpc.call request to nova-conductor\nto fetch instance info such as host ID and flavor
queue -> conductor: Nova-conductor picks the request form the queue
conductor -> novadb: Request host info
novadb --> conductor: Return requested host info
conductor -> queue: Send request to nova-compute on the target host
queue -> compute: Nova-compute picks the requested instance info
end

group Fetching VM Images
compute -> glance: Pass auth-token, get image URL by ID,\nand upload image from image storage
glance <-> keystone: Validate auth-token
glance --> compute: Return the image metadata
end

group Allocating Network Resources
compute -> network: Pass auth-token, allocate/configure network resources\nfor the instance
network <-> keystone: Validate auth-token
network --> compute: Return the requested network resources (ports etc.)
end

group Allocating Block Storage
compute -> cinder: Pass auth-token, attach storage volumes to the instance
cinder <-> keystone: Validate auth-token
cinder --> compute: Return the requested block storage info
end

compute -> hypervisor: Generate data for hypervisor driver,\nand executes request on Hypervisor\nvia libvirt or api

@enduml